import { GameAudio } from './audio';
import { areaAt, checkpoints, makeEnemies, platforms, WORLD_HEIGHT, WORLD_WIDTH } from './level';
import type { AreaId, Enemy, GameSettings, GameSnapshot, InputState, Particle, Player, Platform } from './types';

const VW = 1280;
const VH = 720;
const clamp = (v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp = (a:number,b:number,t:number)=>a+(b-a)*t;
const hit=(a:{x:number;y:number;w:number;h:number},b:{x:number;y:number;w:number;h:number})=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;

type Input = InputState & { special?: boolean };
type Anim = 'idle'|'run'|'jump'|'fall'|'dash'|'attack1'|'attack2'|'attack3'|'flare'|'special'|'hurt';

const startPlayer=():Player=>({x:150,y:570,w:30,h:54,vx:0,vy:0,facing:1,grounded:false,coyote:0,jumpBuffer:0,dashTimer:0,dashCooldown:0,attackTimer:0,attackCooldown:0,burstTimer:0,burstCooldown:0,veilTimer:0,veilCooldown:0,health:4,maxHealth:4,lantern:100,maxLantern:100,invuln:0,hurtFlash:0,landTimer:0,runTime:0,hurtTimer:0});

const story=[
 {x:0,k:'THE FIRST WAKING',l:'The lantern is warm. Someone was holding it before you.',d:4.8},
 {x:720,k:'THE HOLLOW',l:'A bell rope sways without wind. The keeper left in a hurry.',d:3.8},
 {x:1560,k:'THE SHIFTING HALL',l:'Another bearer marked the stones: not a map. A warning.',d:4.4},
 {x:2740,k:'THE SUNKEN GARDEN',l:'Roots drink from the old road. Something underneath remembers.',d:4.2},
 {x:3420,k:'THE CHAPEL',l:'Three lanterns. Three names scratched away.',d:4.2},
 {x:4300,k:'THE DESCENT',l:'The ghosts point down. They do not follow.',d:3.8},
 {x:5700,k:'THE BELL CHAMBER',l:'The bell does not call the dead. It keeps them here.',d:4.2},
];

export class FlikkerEngine {
 canvas:HTMLCanvasElement; ctx:CanvasRenderingContext2D; player=startPlayer(); enemies:Enemy[]=makeEnemies(); particles:Particle[]=[];
 input:Input={left:false,right:false,jump:false,dash:false,attack:false,burst:false,pause:false,special:false};
 settings:GameSettings={reducedFlicker:false,screenShake:true,brightness:1,volume:.42,touchControls:true};
 camera={x:0,y:0,shake:0}; time=0; last=0; hitStop=0; mode:'title'|'playing'|'paused'|'ending'='title';
 toast='The light remembers the way'; toastTimer=4; checkpoint=0; bossDefeated=false;
 storyKicker=story[0].k; storyLine=story[0].l; storyTimer=0; storyBeat=0; ghostGesture:'wait'|'point'|'watch'|'vanish'='wait'; endingTimer=0;
 onSnapshot:(s:GameSnapshot)=>void=()=>{};
 private audio=new GameAudio(); private raf=0; private lastArea:AreaId='THE THRESHOLD'; private burstRing=0; private specialRing=0; private snapshotClock=0; private lastSnapshotMode=this.mode;
 private combo=0; private comboWindow=0; private specialTimer=0; private specialCooldown=0; private anim:Anim='idle'; private dashTrail:Array<{x:number;y:number;a:number}>=[];
 private readonly dustSeed=Array.from({length:90},(_,i)=>({x:(i*83)%VW,y:35+((i*47)%470),s:.25+(i%7)*.09}));
 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable');this.ctx=c;this.resize();}
 start(){this.resize();window.addEventListener('resize',this.resize);window.addEventListener('keydown',this.onSpecialKey);this.raf=requestAnimationFrame(this.loop);}
 destroy(){window.removeEventListener('resize',this.resize);window.removeEventListener('keydown',this.onSpecialKey);cancelAnimationFrame(this.raf);}
 private onSpecialKey=(e:KeyboardEvent)=>{if(e.code==='KeyE'&&!e.repeat&&this.mode==='playing')this.input.special=true;};
 resize=()=>{const d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(this.canvas.clientWidth*d));this.canvas.height=Math.max(1,Math.floor(this.canvas.clientHeight*d));};
 begin(){this.audio.init();this.mode='playing';this.player=startPlayer();this.enemies=makeEnemies();this.particles=[];this.checkpoint=0;this.bossDefeated=false;this.lastArea='THE THRESHOLD';this.camera.x=0;this.combo=0;this.specialCooldown=0;this.toast='The light remembers the way';this.toastTimer=3.4;this.storyBeat=0;this.storyTimer=story[0].d;this.storyKicker=story[0].k;this.storyLine=story[0].l;this.endingTimer=0;this.addBurst(180,610,'gold',28);this.onSnapshot(this.getSnapshot());}
 setMode(m:'title'|'playing'|'paused'|'ending'){this.mode=m;}
 setSettings(s:GameSettings){this.settings=s;this.audio.setVolume(s.volume);}
 setInput(i:Partial<Input>){this.input={...this.input,...i};}
 touchAction(a:keyof Input,pressed=true){if(a==='pause'){this.mode=this.mode==='paused'?'playing':'paused';return;}this.setInput({[a]:pressed});}
 getSnapshot():GameSnapshot{const boss=this.enemies.find(e=>(e.kind==='warden'||e.kind==='eater')&&!e.dead)??this.enemies.find(e=>e.kind==='eater');const g=this.ghostState();return{mode:this.mode,area:areaAt(this.player.x),lantern:this.player.lantern,health:this.player.health,bossHealth:boss?.hp??0,bossMaxHealth:boss?.maxHp??9,checkpoint:this.checkpoint,toast:this.toastTimer>0?this.toast:'',storyKicker:this.storyKicker,storyLine:this.storyLine,storyTimer:this.storyTimer,storyBeat:this.storyBeat,ghostVisible:g.visible,ghostGesture:this.ghostGesture,progress:clamp(this.player.x/(WORLD_WIDTH-500),0,1)};}
 private loop=(now:number)=>{const dt=Math.min((now-this.last)/1000||.016,.034);this.last=now;this.time+=dt;if(this.mode==='playing')this.update(dt);this.render();this.snapshotClock+=dt;if(this.snapshotClock>.075||this.mode!==this.lastSnapshotMode){this.snapshotClock=0;this.lastSnapshotMode=this.mode;this.onSnapshot(this.getSnapshot());}this.raf=requestAnimationFrame(this.loop);};
 private update(dt:number){if(this.hitStop>0){this.hitStop-=dt;this.updateParticles(dt);return;}const p=this.player;const wasGrounded=p.grounded;
  p.coyote=p.grounded?.12:Math.max(0,p.coyote-dt);p.jumpBuffer=this.input.jump?.12:Math.max(0,p.jumpBuffer-dt);p.dashCooldown=Math.max(0,p.dashCooldown-dt);p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.burstCooldown=Math.max(0,p.burstCooldown-dt);this.specialCooldown=Math.max(0,this.specialCooldown-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);p.attackTimer=Math.max(0,p.attackTimer-dt);p.burstTimer=Math.max(0,p.burstTimer-dt);p.invuln=Math.max(0,p.invuln-dt);p.hurtFlash=Math.max(0,p.hurtFlash-dt);p.landTimer=Math.max(0,(p.landTimer??0)-dt);p.hurtTimer=Math.max(0,(p.hurtTimer??0)-dt);this.specialTimer=Math.max(0,this.specialTimer-dt);
  if(this.toastTimer>0)this.toastTimer-=dt;if(this.storyTimer>0)this.storyTimer-=dt;this.advanceStory();
  if(this.input.jump&&p.jumpBuffer>0&&p.coyote>0){p.vy=-635;p.grounded=false;p.coyote=0;p.jumpBuffer=0;this.audio.tone(270,.12,'triangle',.05,90);this.addDust(p.x+15,p.y+p.h,7,'#d8d5bd');}
  if(!this.input.jump&&p.vy<-280)p.vy+=990*dt;
  const move=(this.input.right?1:0)-(this.input.left?1:0);if(move){p.facing=move;p.vx=lerp(p.vx,move*275,Math.min(1,dt*13));p.runTime=(p.runTime??0)+dt*10;}else{p.vx=lerp(p.vx,0,Math.min(1,dt*11));p.runTime=0;}
  if(this.input.dash&&p.dashCooldown<=0&&!this.specialTimer){p.dashTimer=.18;p.dashCooldown=.68;p.vx=p.facing*650;p.vy=0;p.invuln=Math.max(p.invuln,.2);this.anim='dash';this.audio.dash();this.addDashTrail();this.addDust(p.x+(p.facing<0?p.w:0),p.y+p.h-5,16,'#e6d38d');}
  if(p.dashTimer>0){p.dashTimer-=dt;p.vx=p.facing*650;p.vy=0;this.addDashTrail();}else if(this.specialTimer<=0)p.vy+=1650*dt;
  if(this.input.attack&&p.attackCooldown<=0&&this.specialTimer<=0)this.startComboAttack();
  if(this.input.burst&&p.burstCooldown<=0&&p.lantern>=18){p.burstTimer=.5;p.burstCooldown=1.05;p.lantern=Math.max(0,p.lantern-18);this.burstRing=1;this.anim='flare';this.audio.burst();this.addBurst(p.x+p.w/2,p.y+26,'flare',38);this.flashEnemies(true);}
  if(this.input.special&&this.specialCooldown<=0&&p.lantern>=28)this.startLumenStep();
  p.lantern=clamp(p.lantern-dt*(.46+(this.lastArea==='SHIFTING HALL'?.14:0)),0,p.maxLantern);
  if(p.grounded&&Math.abs(p.vx)>38&&Math.random()<dt*5)this.addDust(p.x+15,p.y+p.h,1,'#707b77');
  const prevY=p.y;p.x+=p.vx*dt;p.x=clamp(p.x,-48,WORLD_WIDTH-p.w-20);p.y+=p.vy*dt;p.grounded=false;this.resolveVertical(p,prevY,platforms);if(p.y>WORLD_HEIGHT)this.respawn();
  if(!wasGrounded&&p.grounded){p.landTimer=.18;this.addDust(p.x+15,p.y+p.h,12,'#a7aea0');this.audio.tone(105,.08,'triangle',.035,-30);}
  this.updateEnemies(dt);this.updateParticles(dt);this.updateCheckpoints();this.updateGhost(dt);this.burstRing=Math.max(0,this.burstRing-dt*2.5);this.specialRing=Math.max(0,this.specialRing-dt*2.8);
  const area=areaAt(p.x);if(area!==this.lastArea){this.lastArea=area;this.toast=area;this.toastTimer=2.8;this.addBurst(p.x,p.y,'gold',20);}
  const eater=this.enemies.find(e=>e.kind==='eater');if(eater?.dead&&!this.bossDefeated){this.bossDefeated=true;this.storyKicker='THE LIGHT REMEMBERS';this.storyLine='Inside the Eater: a name, still warm. “Mara. Last bearer.”';this.storyTimer=6.5;this.storyBeat=7;this.toast='THE CHAPEL OPENS';this.toastTimer=4;this.endingTimer=7;this.camera.shake=this.settings.screenShake?1:0;this.addBurst(eater.x,eater.y+70,'flare',70);try{localStorage.setItem('flikker-progress','chapel-open');}catch{}}
  if(this.bossDefeated){this.endingTimer-=dt;if(this.endingTimer<=0)this.mode='ending';}
  this.camera.x=lerp(this.camera.x,clamp(p.x-VW*.35,0,WORLD_WIDTH-VW),Math.min(1,dt*4.5));this.camera.shake=Math.max(0,this.camera.shake-dt*3.2);this.audio.tension(p.lantern/p.maxLantern);
  this.input.jump=false;this.input.dash=false;this.input.attack=false;this.input.burst=false;this.input.special=false;
 }
 private startComboAttack(){const p=this.player;if(this.comboWindow<=0)this.combo=0;this.combo=(this.combo%3)+1;this.comboWindow=.42;p.attackTimer=.31;p.attackCooldown=.22;this.anim=(`attack${this.combo}`) as Anim;this.audio.attack();const damage=this.combo===3?2:1;const range=this.combo===3?92:74;const hb={x:p.facing>0?p.x+8:p.x-range+8,y:p.y+(this.combo===3?-4:4),w:range,h:this.combo===3?66:54};for(const e of this.enemies){if(e.dead||!hit(hb,e))continue;if((e.kind==='eater'||e.kind==='warden')&&!e.vulnerable)continue;e.hp-=damage;e.hitFlash=.22;e.vx=p.facing*(260+this.combo*60);e.vy=this.combo===3?-360:-210;this.hitStop=.07+this.combo*.015;this.camera.shake=this.settings.screenShake?.22+.08*this.combo:0;this.audio.hit();this.addSparks(e.x+e.w/2,e.y+e.h/2,this.combo===3?'#d8f0d8':'#e8c87b',10+this.combo*3);if(e.hp<=0){e.dead=true;this.addBurst(e.x+e.w/2,e.y+e.h/2,'flare',34);this.toast=e.kind==='eater'?'THE HUNGER BREAKS':e.kind==='warden'?'THE BELL GOES SILENT':'THE DARK LETS GO';this.toastTimer=1.7;}}this.addSlashArc(p.x+p.facing*28,p.y+24,this.combo);}
 private startLumenStep(){const p=this.player;p.lantern-=28;this.specialCooldown=2.2;this.specialTimer=.34;p.invuln=.42;p.dashTimer=0;p.vy=-80;p.vx=p.facing*720;this.specialRing=1;this.anim='special';this.audio.dash();this.addBurst(p.x+p.w/2,p.y+p.h/2,'flare',24);for(const e of this.enemies){if(e.dead||!hit({x:p.x-28,y:p.y-12,w:96,h:82},e))continue;e.hp-=2;e.hitFlash=.3;e.vx=p.facing*420;e.vy=-280;this.addSparks(e.x+e.w/2,e.y+e.h/2,'#d6f3dd',18);if(e.hp<=0)e.dead=true;}this.camera.shake=this.settings.screenShake?.55:0;this.toast='LUMEN STEP';this.toastTimer=.8;}
 private resolveVertical(body:{x:number;y:number;w:number;h:number;vy:number;grounded:boolean},previousY:number,surfaces:Platform[]){if(body.vy<0)return;let landing:Platform|null=null;for(const s of surfaces){const y=this.platformY(s.x,s.y);const crossed=previousY+body.h<=y+4&&body.y+body.h>=y;if(crossed&&body.x+body.w>s.x+3&&body.x<s.x+s.w-3&&(!s.oneWay||previousY+body.h<=y+2)){if(!landing||y<this.platformY(landing.x,landing.y))landing=s;}}if(landing){body.y=this.platformY(landing.x,landing.y)-body.h;body.vy=0;body.grounded=true;}}
 private platformY(x:number,y:number){return x>1600&&x<3000?y+Math.sin(this.time*.9+x*.012)*7:y;}
 private advanceStory(){if(this.bossDefeated||this.storyBeat>=story.length-1)return;const n=story[this.storyBeat+1];if(this.player.x>=n.x){this.storyBeat++;this.storyKicker=n.k;this.storyLine=n.l;this.storyTimer=n.d;this.toast=n.k;this.toastTimer=2.2;this.addBurst(this.player.x,this.player.y,'gold',18);this.audio.tone(184,.3,'sine',.04,50);}}
 private updateCheckpoints(){for(let i=0;i<checkpoints.length;i++){if(this.player.x>checkpoints[i].x-100&&i>this.checkpoint){this.checkpoint=i;checkpoints[i].activated=true;this.player.health=this.player.maxHealth;this.player.lantern=Math.min(100,this.player.lantern+40);this.toast=`checkpoint · ${checkpoints[i].area.toLowerCase()}`;this.toastTimer=2.7;this.addBurst(checkpoints[i].x,checkpoints[i].y-45,'gold',36);}}}
 private respawn(){const c=checkpoints[this.checkpoint];this.player.x=c.x;this.player.y=c.y-this.player.h-6;this.player.vx=0;this.player.vy=0;this.player.health=this.player.maxHealth;this.player.lantern=Math.max(48,this.player.lantern);this.player.invuln=1;this.toast='The lantern pulls you back';this.toastTimer=2.2;this.addBurst(this.player.x,this.player.y+35,'flare',30);}
 private updateEnemies(dt:number){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer-=dt;e.attackWindup=Math.max(0,e.attackWindup-dt);e.phase=(e.phase??0)+dt;const d=p.x-e.x;const illuminated=Math.hypot(p.x-e.x,p.y-e.y)<200+p.lantern*1.55||p.burstTimer>0||this.specialTimer>0;if(e.kind!=='eater'&&e.kind!=='warden'&&!illuminated){e.vx=lerp(e.vx,0,dt*3);continue;}e.facing=d<0?-1:1;
   if(e.kind==='eater'||e.kind==='warden'){if(Math.abs(d)<520)e.alert=1;const w=e.kind==='warden';if(e.attackTimer<0){e.attackWindup=w?.72:.6;e.attackTimer=w?2.0:2.35;this.toast=w?'THE BELL WARDEN TURNS':'THE EATER STIRS';this.toastTimer=.8;this.audio.boss();}if(e.attackWindup<=0&&e.attackTimer>(w?1.1:2.2)&&Math.abs(d)<(w?600:540))this.hurtPlayer(1,Math.sign(d)||1);e.vulnerable=p.burstTimer>0||this.specialTimer>0||e.attackWindup>.1;e.vx=lerp(e.vx,clamp(d*(w?.55:.42),-145,145),dt*1.6);
   }else if(e.kind==='watcher'){e.vx=lerp(e.vx,0,dt*4);if(e.attackTimer<0&&Math.abs(d)<450){e.attackTimer=2.5;e.attackWindup=.62;this.toast='A WATCHER TURNS';this.toastTimer=.65;}if(e.attackWindup>.18&&e.attackWindup<.22&&Math.abs(d)<430)this.hurtPlayer(1,Math.sign(d)||1);e.vulnerable=e.attackWindup>.3;
   }else if(e.kind==='skitter'){e.vx=lerp(e.vx,clamp(d*1.4,-180,180),dt*2.8);if(e.attackTimer<0&&Math.abs(d)<120){e.attackTimer=1.5;e.attackWindup=.24;}if(e.attackWindup<=0&&e.attackTimer>1.28&&Math.abs(d)<125)this.hurtPlayer(1,Math.sign(d)||1);e.vulnerable=e.hitFlash>0;
   }else{e.alert=clamp(e.alert+dt,0,1);e.vx=lerp(e.vx,clamp(d*.8,-110,110),dt*1.8);if(e.attackTimer<0&&Math.abs(d)<85){e.attackTimer=1.6;e.attackWindup=.3;}if(e.attackWindup<=0&&e.attackTimer>1.32&&Math.abs(d)<90)this.hurtPlayer(1,Math.sign(d)||1);e.vulnerable=true;}
   const py=e.y;e.x+=e.vx*dt;e.y+=e.vy*dt;e.vy+=1500*dt;e.grounded=false;e.x=clamp(e.x,0,WORLD_WIDTH-e.w);this.resolveVertical(e,py,platforms);if(e.y>WORLD_HEIGHT){e.y=0;e.vy=0;}if(e.kind!=='eater'&&hit(p,e)&&p.invuln<=0)this.hurtPlayer(1,Math.sign(p.x-e.x)||1);
  }}
 private hurtPlayer(dmg:number,dir:number){const p=this.player;if(p.invuln>0||this.specialTimer>0)return;p.health-=dmg;p.invuln=.85;p.hurtFlash=.35;p.hurtTimer=.3;p.vx=dir*300;p.vy=-280;this.anim='hurt';this.camera.shake=this.settings.screenShake?.8:0;this.hitStop=.075;this.audio.hurt();this.addSparks(p.x,p.y+20,'#dce9de',10);if(p.health<=0)this.respawn();}
 private flashEnemies(fromFlare=false){for(const e of this.enemies){if(e.dead)continue;if(Math.hypot(this.player.x-e.x,this.player.y-e.y)<(fromFlare?340:320)){e.alert=1;e.vulnerable=true;if(e.kind==='eater'||e.kind==='warden')e.attackWindup=.01;this.addMote(e.x+e.w/2,e.y+e.h/2);}}}
 private ghostState(){const a=[340,980,1920,2880,3740,4780,5850,7040];let i=0;for(let n=0;n<a.length;n++)if(this.player.x>a[n]-180)i=n;const x=a[i],near=Math.abs(this.player.x-x),visible=!this.bossDefeated&&this.player.x>x-230&&this.player.x<x+175;this.ghostGesture=near<70?'watch':near<135?'wait':'point';if(near<35)this.ghostGesture='vanish';return{x,y:465-(i%2)*56,visible};}
 private updateGhost(dt:number){const g=this.ghostState();if(g.visible&&Math.random()<dt*1.2)this.addMote(g.x,g.y);}
 private addMote(x:number,y:number){this.particles.push({x:x+(Math.random()-.5)*30,y:y+(Math.random()-.5)*40,vx:(Math.random()-.5)*12,vy:-8-Math.random()*18,life:.7+Math.random()*.8,maxLife:1.5,size:1+Math.random()*2,color:'#b9e7d2',gravity:-10});}
 private addDust(x:number,y:number,n:number,color='#9da79e'){for(let i=0;i<n;i++)this.particles.push({x:x+(Math.random()-.5)*28,y:y+Math.random()*7,vx:(Math.random()-.5)*35,vy:-Math.random()*30,life:.45+Math.random()*.55,maxLife:1,size:1+Math.random()*2.5,color,gravity:-5});}
 private addSparks(x:number,y:number,color:string,n:number){for(let i=0;i<n;i++)this.particles.push({x,y,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,life:.18+Math.random()*.35,maxLife:.5,size:1+Math.random()*2.5,color});}
 private addBurst(x:number,y:number,kind:'gold'|'flare'='gold',n=30){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*170;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.45+Math.random()*.55,maxLife:1,size:1+Math.random()*3,color:kind==='flare'?(Math.random()>.25?'#e5f4dc':'#e9c96f'):(Math.random()>.25?'#d7d0a0':'#8caea1')});}}
 private addSlashArc(x:number,y:number,step:number){for(let i=0;i<15;i++){const a=-1.15+i/14*1.9;this.particles.push({x:x+Math.cos(a)*22,y:y+Math.sin(a)*22,vx:Math.cos(a)*25,vy:Math.sin(a)*25,life:.13+step*.02,maxLife:.18+step*.02,size:2+step*.35,color:step===3?'#d7f0d9':'#e9c87d'});}}
 private addDashTrail(){const p=this.player;this.dashTrail.push({x:p.x+p.w/2,y:p.y+p.h/2,a:1});if(this.dashTrail.length>12)this.dashTrail.shift();}
 private updateParticles(dt:number){this.particles=this.particles.filter(q=>q.life>0).slice(-360);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=(q.gravity??280)*dt;}this.dashTrail=this.dashTrail.map(t=>({...t,a:t.a-dt*5})).filter(t=>t.a>0);}
 private render(){const c=this.ctx,s=Math.min(this.canvas.width/VW,this.canvas.height/VH),ox=(this.canvas.width-VW*s)/2,oy=(this.canvas.height-VH*s)/2;c.save();c.clearRect(0,0,this.canvas.width,this.canvas.height);c.translate(ox,oy);c.scale(s,s);const sh=this.settings.screenShake?this.camera.shake*(Math.random()-.5)*8:0;c.translate(sh,sh*.45);this.drawSky(c);c.save();c.translate(-this.camera.x*.08,0);this.drawFar(c);c.restore();c.save();c.translate(-this.camera.x*.28,0);this.drawMid(c);c.restore();c.save();c.translate(-this.camera.x,0);this.drawWorld(c);c.restore();this.drawFog(c);this.drawDarkness(c,ox,oy,s);c.restore();}
 private drawSky(c:CanvasRenderingContext2D){const g=c.createLinearGradient(0,0,0,VH);g.addColorStop(0,'#050b16');g.addColorStop(.45,'#101b27');g.addColorStop(1,'#27302d');c.fillStyle=g;c.fillRect(0,0,VW,VH);const moon=c.createRadialGradient(880,170,4,880,170,300);moon.addColorStop(0,'rgba(206,230,220,.2)');moon.addColorStop(1,'rgba(206,230,220,0)');c.fillStyle=moon;c.fillRect(0,0,VW,VH);c.fillStyle='rgba(204,220,212,.5)';for(const st of this.dustSeed){const x=(st.x+this.time*st.s*5)%VW,y=st.y+Math.sin(this.time*st.s+st.x)*4;c.globalAlpha=.12+(st.x%6)*.035;c.fillRect(x,y,st.x%7===0?2:1,1);}c.globalAlpha=1;}
 private drawFar(c:CanvasRenderingContext2D){c.fillStyle='#0d1822';for(let x=-300;x<WORLD_WIDTH+500;x+=240){const h=130+Math.abs((x*7)%150);c.beginPath();c.moveTo(x,600);c.lineTo(x+20,600-h);c.lineTo(x+80,600-h-18);c.lineTo(x+155,600);c.closePath();c.fill();}c.strokeStyle='rgba(145,175,165,.13)';c.lineWidth=3;for(let x=120;x<WORLD_WIDTH;x+=620)this.arch(c,x,580,160,250,'rgba(145,175,165,.13)');}
 private drawMid(c:CanvasRenderingContext2D){for(let x=-80;x<WORLD_WIDTH+500;x+=360){const h=100+(Math.sin(x*.08)+1)*35;c.fillStyle='#141f25';c.fillRect(x,625-h,24,h);c.fillRect(x+108,625-h*.72,27,h*.72);c.fillStyle='#1d2a2d';c.fillRect(x-12,625-h,152,10);c.strokeStyle='rgba(93,133,121,.2)';c.lineWidth=2;c.beginPath();c.moveTo(x+10,625);c.quadraticCurveTo(x+60,535,x+114,625);c.stroke();}}
 private arch(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string){c.strokeStyle=color;c.lineWidth=7;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-h+45);c.quadraticCurveTo(x+w/2,y-h-34,x+w,y-h+45);c.lineTo(x+w,y);c.stroke();}
 private drawWorld(c:CanvasRenderingContext2D){this.drawArchitecture(c);for(const p of platforms)this.drawPlatform(c,p);this.drawCheckpoints(c);this.drawGhost(c);for(const e of this.enemies)if(!e.dead)this.drawEnemy(c,e);this.drawPlayer(c);for(const q of this.particles){c.globalAlpha=clamp(q.life/q.maxLife,0,1);c.fillStyle=q.color;c.beginPath();c.arc(q.x,q.y,q.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 private drawArchitecture(c:CanvasRenderingContext2D){const a=areaAt(this.player.x);if(a==='THE THRESHOLD'||a==='THE HOLLOW'){this.arch(c,520,662,190,290,'rgba(102,125,116,.36)');c.fillStyle='#1f2b2c';c.fillRect(610,475,13,188);c.strokeStyle='#77795f';c.lineWidth=2;c.beginPath();c.moveTo(615,474);c.lineTo(657,434);c.lineTo(691,518);c.stroke();}if(a==='SHIFTING HALL'){for(let x=1720;x<2940;x+=210){c.fillStyle='#263331';c.fillRect(x,390,25,270);c.fillRect(x+125,430,19,230);c.strokeStyle='rgba(190,165,108,.2)';c.strokeRect(x+26,455,98,68);}}if(a==='THE SUNKEN GARDEN'){c.strokeStyle='rgba(79,120,89,.58)';c.lineWidth=4;for(let x=3080;x<3910;x+=88){c.beginPath();c.moveTo(x,700);c.bezierCurveTo(x-12,622,x+30,574,x+11,510);c.stroke();}c.fillStyle='rgba(65,95,73,.35)';for(let x=3110;x<3900;x+=130)c.fillRect(x,450+(x%80),9,208);}if(a==='THE CHAPEL'||a==='THE DESCENT'||a==='BELL CHAMBER'||a==='EATER ARENA'){c.fillStyle='#18232a';c.fillRect(4300,290,18,360);c.fillRect(4660,250,20,400);this.arch(c,4840,665,230,375,'rgba(110,140,130,.34)');}if(a==='THE CHAPEL'||a==='BELL CHAMBER'){c.strokeStyle='rgba(210,181,112,.3)';c.lineWidth=3;for(let x=3420;x<4330;x+=220){c.beginPath();c.moveTo(x,300);c.lineTo(x,665);c.moveTo(x+118,350);c.lineTo(x+118,665);c.stroke();}c.beginPath();c.moveTo(5800,230);c.lineTo(5800,520);c.arc(5800,545,56,Math.PI,Math.PI*2);c.stroke();}}
 private drawGhost(c:CanvasRenderingContext2D){const s=this.ghostState();if(!s.visible)return;const x=s.x,y=s.y+Math.sin(this.time*1.5)*5;c.save();c.translate(x,y);c.globalCompositeOperation='screen';const h=c.createRadialGradient(0,-15,3,0,-15,95);h.addColorStop(0,'rgba(220,255,235,.28)');h.addColorStop(1,'rgba(130,215,190,0)');c.fillStyle=h;c.beginPath();c.arc(0,-15,95,0,Math.PI*2);c.fill();c.fillStyle='rgba(176,224,204,.9)';c.beginPath();c.moveTo(-24,-5);c.quadraticCurveTo(-18,-28,0,-30);c.quadraticCurveTo(18,-28,24,-5);c.lineTo(32,34);c.quadraticCurveTo(12,28,0,46);c.quadraticCurveTo(-12,28,-32,34);c.closePath();c.fill();c.fillStyle='#183c3a';c.beginPath();c.ellipse(0,-27,7,5,0,0,Math.PI*2);c.fill();c.fillStyle='#efffe9';c.fillRect(-4,-28,2,2);c.fillRect(2,-28,2,2);if(this.ghostGesture==='point'){c.strokeStyle='#e5ffe7';c.lineWidth=3;c.beginPath();c.moveTo(16,0);c.lineTo(46,-24);c.stroke();}else if(this.ghostGesture==='wait'){c.strokeStyle='rgba(229,255,231,.75)';c.lineWidth=2;c.beginPath();c.arc(0,-8,35+Math.sin(this.time*3)*2,0,Math.PI*2);c.stroke();}c.restore();}
 private drawPlatform(c:CanvasRenderingContext2D,p:Platform){const y=this.platformY(p.x,p.y);const water=p.material==='water',wood=p.material==='wood';c.fillStyle=water?'#243e43':wood?'#40382d':'#27343a';c.beginPath();c.moveTo(p.x,y);c.lineTo(p.x+p.w,y);c.lineTo(p.x+p.w-10,y+p.h);c.lineTo(p.x+10,y+p.h);c.closePath();c.fill();const shine=water?'#57847b':'#52615a';c.fillStyle=shine;c.beginPath();c.moveTo(p.x-3,y);c.lineTo(p.x+p.w+3,y);c.lineTo(p.x+p.w-12,y+9);c.lineTo(p.x+15,y+11);c.closePath();c.fill();c.strokeStyle=water?'rgba(180,220,205,.4)':'rgba(171,175,148,.22)';c.lineWidth=1;for(let x=p.x+24;x<p.x+p.w-12;x+=52){c.beginPath();c.moveTo(x,y+15);c.lineTo(x-8,y+p.h-9);c.stroke();}if(p.moss){c.strokeStyle='#66805f';c.lineWidth=2;for(let x=p.x+15;x<p.x+p.w-14;x+=28){c.beginPath();c.moveTo(x,y+5);c.quadraticCurveTo(x-3,y-5,x+4,y-13);c.stroke();}}if(water){c.strokeStyle='rgba(190,225,210,.3)';for(let x=p.x+20;x<p.x+p.w;x+=63){c.beginPath();c.moveTo(x,y+25);c.quadraticCurveTo(x+16,y+20,x+34,y+26);c.stroke();}}}
 private drawCheckpoints(c:CanvasRenderingContext2D){for(let i=0;i<checkpoints.length;i++){const q=checkpoints[i],active=i<=this.checkpoint;c.strokeStyle=active?'rgba(229,190,104,.8)':'rgba(120,140,132,.25)';c.lineWidth=2;c.beginPath();c.moveTo(q.x,q.y);c.lineTo(q.x,q.y-66);c.stroke();const r=7+Math.sin(this.time*3+i)*1.5;c.fillStyle=active?'rgba(239,198,111,.22)':'rgba(120,150,140,.06)';c.beginPath();c.arc(q.x,q.y-71,r*3,0,Math.PI*2);c.fill();c.stroke();}}
 private drawEnemy(c:CanvasRenderingContext2D,e:Enemy){const cx=e.x+e.w/2,cy=e.y+e.h/2,f=e.facing??1;c.save();c.translate(cx,cy);c.scale(f,1);const hitFlash=e.hitFlash>0,pulse=Math.sin(this.time*5+(e.phase??0))*2,tele=e.attackWindup>.05;const glow=e.vulnerable&&((e.kind==='eater'||e.kind==='warden'))?18:0;if(glow){c.fillStyle='rgba(211,242,216,.1)';c.beginPath();c.arc(0,-20,70+glow+pulse,0,Math.PI*2);c.fill();}if(e.kind==='eater'){c.fillStyle=hitFlash?'#e9f1df':'#17282d';c.beginPath();c.moveTo(-58,70);c.quadraticCurveTo(-75,10,-60,-48);c.quadraticCurveTo(-44,-92,0,-100);c.quadraticCurveTo(44,-92,60,-48);c.quadraticCurveTo(75,10,58,70);c.lineTo(0,78);c.closePath();c.fill();c.strokeStyle='rgba(173,211,194,.35)';c.lineWidth=3;for(let i=-2;i<=2;i++){c.beginPath();c.moveTo(i*18,-64);c.quadraticCurveTo(i*24,-4,i*17,52);c.stroke();}c.fillStyle='#070d12';c.beginPath();c.ellipse(0,-34,42,31+Math.sin(this.time*3)*3,0,0,Math.PI*2);c.fill();c.fillStyle=tele?'#ef9d62':'#d6ead3';c.beginPath();c.arc(0,-35,8+pulse*.3,0,Math.PI*2);c.fill();c.strokeStyle=tele?'#ef9a62':'rgba(205,238,211,.65)';c.lineWidth=4;c.beginPath();c.arc(0,-20,86+pulse,Math.PI*.1,Math.PI*.9);c.stroke();}else if(e.kind==='warden'){c.fillStyle=hitFlash?'#e9e0c2':'#1a2c31';c.beginPath();c.moveTo(-45,67);c.lineTo(-39,-33);c.quadraticCurveTo(-30,-70,0,-78);c.quadraticCurveTo(30,-70,39,-33);c.lineTo(45,67);c.lineTo(0,75);c.closePath();c.fill();c.fillStyle='#0a1116';c.beginPath();c.ellipse(0,-39,29,25,0,0,Math.PI*2);c.fill();c.fillStyle=tele?'#ef9d62':'#d9ca87';c.beginPath();c.ellipse(-11,-38,5,3,0,0,Math.PI*2);c.ellipse(11,-38,5,3,0,0,Math.PI*2);c.fill();c.strokeStyle='#cbb26f';c.lineWidth=4;c.beginPath();c.moveTo(-30,-17);c.lineTo(-62,35);c.moveTo(30,-17);c.lineTo(62,35);c.stroke();}else{const big=e.kind==='watcher';c.fillStyle=hitFlash?'#e9dfbc':'#31464a';c.beginPath();c.ellipse(0,0,big?25:29,big?38:18,0,0,Math.PI*2);c.fill();c.fillStyle='#070e13';c.beginPath();c.ellipse(0,-15,big?19:14,big?15:10,0,0,Math.PI*2);c.fill();c.fillStyle=tele?'#ef9d62':'#dcc978';c.beginPath();c.arc(big?0:19,big?-15:-7,big?5:4,0,Math.PI*2);c.fill();c.strokeStyle='#81988d';c.lineWidth=2;c.beginPath();c.moveTo(-20,20);c.lineTo(-35,40);c.moveTo(20,20);c.lineTo(35,40);c.stroke();}c.restore();if(e.hp<e.maxHp&&e.kind!=='eater'){c.fillStyle='rgba(6,12,16,.8)';c.fillRect(e.x-2,e.y-12,e.w+4,5);c.fillStyle='#d2b76e';c.fillRect(e.x,e.y-11,e.w*e.hp/e.maxHp,3);}}
 private drawPlayer(c:CanvasRenderingContext2D){const p=this.player;let a:Anim=this.anim;if(p.hurtTimer&&p.hurtTimer>0)a='hurt';else if(p.dashTimer>0)a='dash';else if(this.specialTimer>0)a='special';else if(p.attackTimer>0)a=this.anim.startsWith('attack')?this.anim:'attack1';else if(p.burstTimer>0)a='flare';else if(!p.grounded)a=p.vy<0?'jump':'fall';else if(Math.abs(p.vx)>35)a='run';else a='idle';const run=Math.sin((p.runTime??0))*(a==='run'?1:0),bob=a==='idle'?Math.sin(this.time*2.2)*1.2:run*2;c.save();for(const t of this.dashTrail){c.globalAlpha=t.a*.2;c.fillStyle='#d9e8d8';c.beginPath();c.arc(t.x,t.y,16,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.translate(p.x+p.w/2,p.y+p.h/2+bob);c.scale(p.facing,1);const lean=a==='dash'?.28:a==='special'?.38:a==='attack3'?-.18:0;c.rotate(lean);if(p.invuln>0&&Math.floor(this.time*20)%2===0)c.globalAlpha=.5;
   c.fillStyle='rgba(224,184,87,.13)';c.beginPath();c.arc(19,3,35+(p.burstTimer>0?20:0),0,Math.PI*2);c.fill();
   const cloak=c.createLinearGradient(-20,-38,20,35);cloak.addColorStop(0,'#47616a');cloak.addColorStop(.45,'#1b303b');cloak.addColorStop(1,'#08151f');c.fillStyle=cloak;c.beginPath();c.moveTo(-18,31);c.quadraticCurveTo(-30,10,-22,-13);c.quadraticCurveTo(-17,-34,0,-38);c.quadraticCurveTo(22,-34,23,-8);c.lineTo(18,32);c.lineTo(8,25);c.lineTo(0,35);c.lineTo(-8,25);c.closePath();c.fill();
   c.strokeStyle='rgba(142,171,166,.75)';c.lineWidth=1.5;c.beginPath();c.moveTo(-15,-2);c.quadraticCurveTo(-5,7,-7,28);c.moveTo(0,-5);c.lineTo(0,29);c.moveTo(15,-1);c.quadraticCurveTo(6,7,8,28);c.stroke();
   c.fillStyle='#9eb4ae';c.beginPath();c.arc(1,-26,13,0,Math.PI*2);c.fill();c.fillStyle='#111d25';c.beginPath();c.moveTo(-15,-29);c.quadraticCurveTo(0,-49,18,-32);c.lineTo(11,-25);c.lineTo(-15,-26);c.closePath();c.fill();
   c.strokeStyle='#7e9890';c.lineWidth=3;c.beginPath();c.moveTo(-8,-4);c.lineTo(-15+run*5,31);c.moveTo(8,-4);c.lineTo(16-run*5,31);c.stroke();
   c.fillStyle='#e2bd62';c.beginPath();c.arc(19,4,6+(p.burstTimer>0?5:0),0,Math.PI*2);c.fill();c.fillStyle='rgba(255,226,141,.3)';c.beginPath();c.arc(19,4,13+(p.burstTimer>0?10:0),0,Math.PI*2);c.fill();
   if(a.startsWith('attack')){const n=Number(a.slice(-1));const ang=n===1?-1.1:n===2?.25:-1.5;const reach=n===3?46:38;c.save();c.translate(18,-3);c.rotate(ang);c.strokeStyle='#dbe9df';c.lineWidth=3;c.beginPath();c.moveTo(-2,0);c.lineTo(reach,14);c.stroke();c.strokeStyle='#f1d68c';c.lineWidth=5;c.beginPath();c.arc(0,0,35+n*4,-1.1,.65);c.stroke();c.restore();}else if(a==='special'){c.strokeStyle='rgba(214,247,222,.9)';c.lineWidth=4;c.beginPath();c.arc(0,0,50+Math.sin(this.time*18)*5,0,Math.PI*2);c.stroke();}else if(a==='flare'){c.strokeStyle='rgba(225,243,219,.85)';c.lineWidth=3;c.beginPath();c.arc(18,4,42+Math.sin(this.time*16)*5,0,Math.PI*2);c.stroke();}
   c.restore();}
 private drawFog(c:CanvasRenderingContext2D){c.save();c.globalCompositeOperation='screen';for(let i=0;i<5;i++){const y=420+i*40+Math.sin(this.time*.2+i)*14,x=(this.time*(8+i*4)+i*230)%(VW+500)-250,g=c.createRadialGradient(x,y,5,x,y,270);g.addColorStop(0,'rgba(170,190,180,.1)');g.addColorStop(1,'rgba(170,190,180,0)');c.fillStyle=g;c.beginPath();c.ellipse(x,y,290,34,0,0,Math.PI*2);c.fill();}c.restore();}
 private drawDarkness(c:CanvasRenderingContext2D,ox:number,oy:number,s:number){const p=this.player,sx=(p.x-this.camera.x+p.w/2)*s+ox,sy=(p.y+p.h/2)*s+oy,e=p.lantern/p.maxLantern;const flick=this.settings.reducedFlicker?1:1+Math.sin(this.time*15.2)*.035+Math.sin(this.time*29.1)*(1-e)*.08;const r=(112+e*165)*flick*s;c.save();c.fillStyle=`rgba(1,5,10,${clamp(.76-e*.2,.48,.78)})`;c.fillRect(0,0,VW,VH);const clear=c.createRadialGradient(sx,sy,r*.08,sx,sy,r);clear.addColorStop(0,'rgba(255,239,188,.25)');clear.addColorStop(.4,'rgba(16,23,27,.08)');clear.addColorStop(1,'rgba(0,0,0,.95)');c.globalCompositeOperation='destination-out';c.fillStyle=clear;c.beginPath();c.arc(sx,sy,r,0,Math.PI*2);c.fill();c.globalCompositeOperation='screen';const bloom=c.createRadialGradient(sx,sy,0,sx,sy,r*.68);bloom.addColorStop(0,'rgba(255,212,123,.28)');bloom.addColorStop(.45,'rgba(255,190,83,.08)');bloom.addColorStop(1,'rgba(255,205,112,0)');c.fillStyle=bloom;c.beginPath();c.arc(sx,sy,r*.68,0,Math.PI*2);c.fill();if(this.burstRing>0){c.strokeStyle=`rgba(215,242,222,${this.burstRing})`;c.lineWidth=3;c.beginPath();c.arc(sx,sy,(1-this.burstRing)*380*s,0,Math.PI*2);c.stroke();}if(this.specialRing>0){c.strokeStyle=`rgba(230,248,225,${this.specialRing})`;c.lineWidth=2;c.beginPath();c.arc(sx,sy,(1-this.specialRing)*250*s,0,Math.PI*2);c.stroke();}c.restore();}
}
