import { areaAt, checkpoints, platforms, WORLD_HEIGHT, WORLD_WIDTH } from './level';
import { actAt, roomAt } from './campaign';
import type { Enemy, GameSettings, GameSnapshot, InputState, Particle, Player, EndingChoice } from './types';

const VW=1280,VH=720, clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v)), lerp=(a:number,b:number,t:number)=>a+(b-a)*t);
const hit=(a:{x:number;y:number;w:number;h:number},b:{x:number;y:number;w:number;h:number})=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
type Mode='title'|'playing'|'paused'|'ending'; type LanternMode='ILLUMINATE'|'REVEAL'|'PULSE'|'MEMORY'|'PURITY';
const story:Array<[string,string,number]>=[
 ['THE FIRST WAKING','The lantern is warm. Someone was holding it before you.',0],['THE HOLLOW','A bell rope sways without wind. The keeper left in a hurry.',720],['THE DARK CAVE','Some things fear being remembered.',1580],['THE MEMORY ROOM','For eight seconds, the dead city remembers how to breathe.',2740],['THE BELL WARDEN','You should not have remembered that.',3920],['THE THRESHOLD','What is real if memories can lie?',5300],['THE MEMORY GARDEN','Every flower disappears when you stop remembering it.',6100],['THE ARCHIVE','Every name here belongs to someone who thought they were the hero.',6840],['THE MIRROR WARD','Your reflection is late. Do not wait for it to catch up.',8400],['THE KEEPER','I was not protecting the Hollow from you. I was protecting you from the Hollow.',10160],['THE EATER','I am not your enemy. I am everything you refused to remember.',10800]
];
const player=():Player=>({x:150,y:560,w:34,h:58,vx:0,vy:0,facing:1,grounded:false,coyote:0,jumpBuffer:0,dashTimer:0,dashCooldown:0,attackTimer:0,attackCooldown:0,burstTimer:0,burstCooldown:0,veilTimer:0,veilCooldown:0,health:4,maxHealth:4,lantern:100,maxLantern:100,invuln:0,hurtFlash:0,landTimer:0,runTime:0,hurtTimer:0});
const makeEnemies=():Enemy[]=>[
 [1,'hollow',1020,540,38,60,3],[2,'skitter',1390,640,52,34,3],[3,'hollow',1730,535,38,60,5],[4,'watcher',2350,555,48,64,5],[5,'hollow',3040,600,38,60,6],[6,'warden',4050,475,104,155,16],[7,'skitter',4880,605,52,34,5],[8,'watcher',6120,500,48,64,6],[10,'warden',7280,505,110,150,18],[11,'hollow',7900,570,38,60,7],[12,'watcher',8540,510,48,64,8],[13,'skitter',9280,575,52,34,8],[14,'hollow',10020,615,38,60,9],[15,'warden',10360,410,110,155,14],[9,'eater',10920,490,150,165,32]
].map(([id,kind,x,y,w,h,hp])=>({id:id as number,kind:kind as Enemy['kind'],x:x as number,y:y as number,w:w as number,h:h as number,vx:0,vy:0,hp:hp as number,maxHp:hp as number,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:1}));

export class FlikkerEngine{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;player=player();enemies=makeEnemies();particles:Particle[]=[];input:InputState={left:false,right:false,jump:false,dash:false,attack:false,burst:false,pause:false,special:false};settings:GameSettings={reducedFlicker:false,screenShake:true,brightness:1,volume:.42,touchControls:true};mode:Mode='title';camera={x:0,shake:0};time=0;last=0;checkpoint=0;bossDefeated=false;endingChoice:EndingChoice=null;endingTimer=0;toast='THE LIGHT REMEMBERS';toastTimer=3;storyBeat=0;storyKicker=story[0][0];storyLine=story[0][1];storyTimer=0;lanternMode:LanternMode='ILLUMINATE';memoryMode=false;pulse=0;lanternThrown=false;lanternX=0;lanternY=0;combo=0;comboWindow=0;hitStop=0;horror=0;redFlash=0;lastArea='THE THRESHOLD' as const;private raf=0;private audio:AudioContext|null=null;onSnapshot:(s:GameSnapshot)=>void=()=>{};
 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable');this.ctx=c;this.resize();}
 start(){this.resize();window.addEventListener('resize',this.resize);this.raf=requestAnimationFrame(this.loop);}
 destroy(){window.removeEventListener('resize',this.resize);cancelAnimationFrame(this.raf);}
 resize=()=>{const d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(this.canvas.clientWidth*d));this.canvas.height=Math.max(1,Math.floor(this.canvas.clientHeight*d));};
 setSettings(s:GameSettings){this.settings=s;} setInput(i:Partial<InputState>){this.input={...this.input,...i};} setMode(m:Mode){this.mode=m;} touchAction(a:keyof InputState,p=true){if(a==='pause'){this.mode=this.mode==='paused'?'playing':'paused';return;}this.setInput({[a]:p});}
 begin(){this.audio=typeof AudioContext!=='undefined'?new AudioContext():null;this.mode='playing';this.player=player();this.enemies=makeEnemies();this.particles=[];this.checkpoint=0;checkpoints.forEach(c=>c.activated=false);this.bossDefeated=false;this.endingChoice=null;this.endingTimer=0;this.camera.x=0;this.time=0;this.storyBeat=0;this.storyKicker=story[0][0];this.storyLine=story[0][1];this.storyTimer=4.8;this.toast='THE LIGHT REMEMBERS';this.toastTimer=2.5;this.lanternMode='ILLUMINATE';this.memoryMode=false;this.lastArea='THE THRESHOLD';this.pulse=0;this.onSnapshot(this.getSnapshot());}
 private tone(f:number){try{if(!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain();o.frequency.value=f;g.gain.value=.025;o.connect(g);g.connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+.06);}catch{}}
 private key=(e:KeyboardEvent)=>{if(this.mode!=='playing')return;if(e.code==='KeyQ'&&!e.repeat){this.cycleMode();e.preventDefault();}if((e.code==='KeyE'||e.code==='KeyL')&&!e.repeat){this.lanternAbility();e.preventDefault();}if(e.code==='KeyR'&&!e.repeat){if(this.lanternThrown)this.lanternReturn();else this.lanternThrow();e.preventDefault();}};
 private cycleMode(){const m:LanternMode[]=['ILLUMINATE','REVEAL','PULSE','MEMORY','PURITY'];this.lanternMode=m[(m.indexOf(this.lanternMode)+1)%m.length];this.toast=this.lanternMode;this.toastTimer=.8;this.tone(440);}
 private lanternAbility(){if(this.player.lantern<8)return;this.player.lantern-=8;switch(this.lanternMode){case'ILLUMINATE':this.pulse=.8;break;case'REVEAL':this.pulse=1.2;this.reveal(500);break;case'PULSE':this.pulse=1.4;this.reveal(600);break;case'MEMORY':this.memoryMode=!this.memoryMode;this.toast=this.memoryMode?'MEMORY / PAST':'PRESENT / RUIN';this.toastTimer=1.3;break;case'PURITY':this.pulse=1;this.reveal(700);this.enemies.forEach(e=>{if(!e.dead)e.vulnerable=true;});break;}this.tone(620);}
 private lanternThrow(){this.lanternThrown=true;this.lanternX=this.player.x+this.player.facing*120;this.lanternY=this.player.y+25;this.toast='LANTERN THROW';this.toastTimer=.7;}
 private lanternReturn(){this.lanternThrown=false;this.toast='LANTERN RETURN';this.toastTimer=.7;}
 getSnapshot():GameSnapshot{const r=roomAt(this.player.x),b=this.boss(),phase=b?this.bossPhase(b):0;return{mode:this.mode,area:areaAt(this.player.x),lantern:this.player.lantern,health:this.player.health,bossHealth:b?.hp??0,bossMaxHealth:b?.maxHp??0,checkpoint:this.checkpoint,toast:this.toastTimer>0?this.toast:'',storyKicker:this.storyKicker,storyLine:this.storyLine,storyTimer:this.storyTimer,storyBeat:this.storyBeat,ghostVisible:this.ghostVisible(),ghostGesture:this.player.x>9700?'watch':this.player.x>8200?'point':'wait',progress:clamp(this.player.x/(WORLD_WIDTH-500),0,1),act:r.act,actQuestion:r.act==='FEAR'?'Can you survive the dark?':r.act==='DOUBT'?'What is real if memories can lie?':'Who are you when memory cannot answer?',roomTitle:r.title,mechanic:r.mechanic,lanternMode:this.lanternMode,memoryMode:this.memoryMode,bossName:this.bossName(b),bossPhase:phase,endingChoice:this.endingChoice};}
 private boss(){return this.enemies.find(e=>(e.kind==='warden'||e.kind==='eater')&&!e.dead);}
 private bossName(e?:Enemy){if(!e)return '';if(e.kind==='eater')return 'THE EATER';if(e.x>10000)return 'THE KEEPER';if(e.x>6800)return 'THE CARTOGRAPHER';return 'THE BELL WARDEN';}
 private bossPhase(e:Enemy){return e.kind==='eater'?Math.min(4,Math.max(1,Math.floor((1-e.hp/e.maxHp)*4)+1)):Math.min(3,Math.max(1,Math.floor((1-e.hp/e.maxHp)*3)+1));}
 private ghostVisible(){return this.player.x>8200&&Math.sin(this.time*1.55)>.73;}
 private loop=(now:number)=>{const dt=Math.min((now-this.last)/1000||.016,.033);this.last=now;this.time+=dt;if(this.mode==='playing')this.update(dt);this.render();this.raf=requestAnimationFrame(this.loop);};
 private update(dt:number){const p=this.player,dir=(this.input.right?1:0)-(this.input.left?1:0);this.toastTimer=Math.max(0,this.toastTimer-dt);this.storyTimer=Math.max(0,this.storyTimer-dt);this.pulse=Math.max(0,this.pulse-dt);this.horror=Math.max(0,this.horror-dt*.35);this.redFlash=Math.max(0,this.redFlash-dt*3);p.invuln=Math.max(0,p.invuln-dt);p.dashCooldown=Math.max(0,p.dashCooldown-dt);p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.burstCooldown=Math.max(0,p.burstCooldown-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);
  this.updateStory();p.coyote=p.grounded?.12:Math.max(0,p.coyote-dt);p.jumpBuffer=this.input.jump?.12:Math.max(0,p.jumpBuffer-dt);
  if(this.input.jump&&p.jumpBuffer>0&&(p.grounded||p.coyote>0)){p.vy=-680;p.grounded=false;p.jumpBuffer=0;this.spawn(p.x,p.y+p.h,8,'#dbe6dd');}
  if(dir){p.facing=dir;p.vx=lerp(p.vx,dir*310,Math.min(1,dt*12));p.runTime=(p.runTime||0)+dt;}else{p.vx=lerp(p.vx,0,Math.min(1,dt*10));p.runTime=0;}
  if(this.input.dash&&p.dashCooldown<=0){p.dashTimer=.18;p.dashCooldown=.82;p.vx=p.facing*760;p.vy=0;p.invuln=.25;this.spawn(p.x,p.y+25,14,'#f2d38d');}
  if(p.dashTimer>0){p.dashTimer-=dt;p.vx=p.facing*760;p.vy=0;}else p.vy+=1700*dt;
  if(this.input.attack&&p.attackCooldown<=0)this.attack();if(this.input.burst&&p.burstCooldown<=0&&p.lantern>=15){p.burstCooldown=1.05;p.lantern-=15;this.pulse=.8;this.reveal(380);this.spawn(p.x+17,p.y+28,30,'#ffd77b');}
  if(this.input.special){this.lanternAbility();this.input.special=false;}
  this.playerMove(dt);this.updateEnemies(dt);this.updateCheckpoints();this.updateParticles(dt);this.updateLantern(dt);
  const a=areaAt(p.x);if(a!==this.lastArea){this.lastArea=a;this.toast=a;this.toastTimer=2.1;this.spawn(p.x,p.y,18,'#e8bd67');}
  const eater=this.enemies.find(e=>e.kind==='eater');if(eater?.dead&&!this.bossDefeated){this.bossDefeated=true;this.toast='THE CHOICE IS YOURS';this.toastTimer=4;this.storyKicker='THE LIGHT REMEMBERS';this.storyLine='Inside the Eater: a name, still warm. Mara. Last bearer.';this.storyTimer=7;this.endingTimer=8;this.endingChoice='FREEDOM';}
  if(this.bossDefeated){this.endingTimer-=dt;if(this.endingTimer<=0)this.mode='ending';}
  this.camera.x=lerp(this.camera.x,clamp(p.x-VW*.42,0,WORLD_WIDTH-VW),Math.min(1,dt*4.5));this.camera.shake=this.settings.screenShake?this.shake:0;this.shake=Math.max(0,this.shake-dt*4);this.input.jump=false;this.input.dash=false;this.input.attack=false;this.input.burst=false;
 }
 private playerMove(dt:number){const p=this.player,ox=p.x,oy=p.y;p.x=clamp(p.x+p.vx*dt,-30,WORLD_WIDTH-p.w-20);this.horizontal(p,ox);p.y+=p.vy*dt;p.grounded=false;this.vertical(p,oy);if(p.y>WORLD_HEIGHT+100)this.respawn();}
 private updateLantern(dt:number){const a=areaAt(this.player.x),safe=a==='THE THRESHOLD'||a==='THE HOLLOW'||a==='THE SUNKEN GARDEN';const drain=(safe?.2:.32)+(this.player.x>7600?.16:0);this.player.lantern=clamp(this.player.lantern+(safe?.55:0)-drain*dt,0,100);if(this.player.lantern<18){this.horror=.7;if(this.toastTimer<=0){this.toast='THE DARK HAS FOUND YOU';this.toastTimer=1.1;}}if(this.memoryMode&&this.player.x>5300&&this.player.x<6680)this.player.lantern=clamp(this.player.lantern+.2,0,100);}
 private updateStory(){for(let i=story.length-1;i>=0;i--)if(this.player.x>=story[i][2]&&i>=this.storyBeat){this.storyBeat=i;this.storyKicker=story[i][0];this.storyLine=story[i][1];this.storyTimer=4.2;this.toast=story[i][0];this.toastTimer=2;break;}}
 private reveal(r:number){for(const e of this.enemies)if(!e.dead&&Math.hypot(this.player.x-e.x,this.player.y-e.y)<r){e.alert=1;e.vulnerable=true;}}
 private attack(){const p=this.player;if(this.comboWindow<=0)this.combo=0;this.combo=this.combo%3+1;this.comboWindow=.48;p.attackCooldown=.19;const range=this.combo===3?112:82,h={x:p.facing>0?p.x+8:p.x-range+28,y:p.y+(this.combo===3?-12:8),w:range,h:this.combo===3?78:54};for(const e of this.enemies){if(e.dead||!hit(h,e)||((e.kind==='warden'||e.kind==='eater')&&!e.vulnerable))continue;let dmg=this.combo===3?3:1;if(this.lanternMode==='PURITY')dmg++;e.hp-=dmg;e.hitFlash=.2;e.vx=p.facing*(280+this.combo*60);e.vy=this.combo===3?-430:-210;this.spawn(e.x+e.w/2,e.y+e.h/2,10,'#ffe2a0');if(e.hp<=0)e.dead=true;}this.toast=this.combo===3?'FALLING STAR':this.combo===2?'RISING LIGHT':'SPARK';this.toastTimer=.35;this.tone(350+this.combo*100);}
 private updateEnemies(dt:number){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer-=dt;const dist=Math.abs(p.x-e.x),d=p.x-e.x;if(e.kind==='warden'||e.kind==='eater'){this.updateBoss(e,dt);continue;}if(e.x>5300&&e.x<6680&&dist<110){p.lantern=clamp(p.lantern-dt*4,0,100);this.horror=.35;}if(e.kind==='watcher'&&e.x>8200)e.y+=Math.sin(this.time*2+e.id)*.2;else if(dist<430||e.alert>0)e.vx=Math.sign(d)*((e.kind==='skitter'?120:70)+(e.x>7600?25:0));else e.vx=Math.sin(this.time+e.id)*10;e.x+=e.vx*dt;this.enemyGround(e);if(dist<82&&e.attackTimer<=0){e.attackTimer=e.kind==='skitter'?.9:1.35;this.damage(1);}}}
 private updateBoss(e:Enemy,dt:number){const p=this.player,phase=this.bossPhase(e);e.phase=phase;if(e.attackTimer>0){e.attackTimer-=dt;return;}e.attackTimer=e.kind==='eater'?.95:1.1;if(e.kind==='eater'){if(phase===1){this.damage(1);this.spawn(e.x,e.y+80,15,'#c27a6a');}else if(phase===2){this.reveal(520);this.damage(1);}else if(phase===3){this.memoryMode=!this.memoryMode;this.horror=1;this.shake=.7;}else{this.pulse=1;this.damage(1);}}else if(e.x>10000){this.toast='THE KEEPER WATCHES';this.toastTimer=.8;this.horror=.55;e.vulnerable=false;this.pulse=.7;}else{this.toast='THE MAP MOVES';this.toastTimer=.7;this.pulse=.5;this.shake=.35;}}
 private damage(n:number){const p=this.player;if(p.invuln>0)return;p.health=clamp(p.health-n,0,p.maxHealth);p.invuln=.55;p.hurtFlash=.25;this.redFlash=.5;this.shake=.45;if(p.health<=0)this.respawn();}
 private updateCheckpoints(){for(let i=0;i<checkpoints.length;i++){const c=checkpoints[i];if(!c.activated&&this.player.x>=c.x){c.activated=true;this.checkpoint=i;this.player.health=this.player.maxHealth;this.player.lantern=this.player.maxLantern;this.toast='LUMEN SHRINE';this.toastTimer=1.2;this.spawn(c.x,c.y-20,24,'#f4cf76');}}}
 private respawn(){const c=checkpoints[this.checkpoint]||checkpoints[0];this.player.x=c.x;this.player.y=c.y-this.player.h-5;this.player.vx=0;this.player.vy=0;this.player.health=this.player.maxHealth;this.player.lantern=65;this.horror=0;this.toast='THE LANTERN BRINGS YOU BACK';this.toastTimer=1.8;}
 private horizontal(b:Player,oldX:number){if(!b.vx)return;for(const s of platforms){if(s.oneWay)continue;if(b.y+b.h<=s.y+5||b.y>=s.y+s.h)continue;if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX+b.w<=s.x&&b.vx>0){b.x=s.x-b.w-.01;b.vx=0;}else if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX>=s.x+s.w&&b.vx<0){b.x=s.x+s.w+.01;b.vx=0;}}}
 private vertical(b:Player,oldY:number){if(b.vy<0)return;let land:any;for(const s of platforms){const crossed=oldY+b.h<=s.y+4&&b.y+b.h>=s.y;if(crossed&&b.x+b.w>s.x+3&&b.x<s.x+s.w-3&&(!s.oneWay||oldY+b.h<=s.y+2)&&(!land||s.y<land.y))land=s;}if(land){b.y=land.y-b.h;b.vy=0;b.grounded=true;}}
 private enemyGround(e:Enemy){const s=platforms.find(q=>e.x+e.w>q.x&&e.x<q.x+q.w&&Math.abs(e.y+e.h-q.y)<14);if(s)e.y=s.y-e.h;}
 private spawn(x:number,y:number,n:number,color:string){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*170;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.55,maxLife:.9,size:1+Math.random()*3,color,gravity:40});}}
 private updateParticles(dt:number){for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=(q.gravity||0)*dt;}this.particles=this.particles.filter(q=>q.life>0);}
 private chooseColor(){return actAt(this.player.x)==='IDENTITY'?'#c88ed8':actAt(this.player.x)==='DOUBT'?'#8ed8d1':'#e6b35d';}
 private render(){const c=this.ctx;c.save();c.clearRect(0,0,this.canvas.width,this.canvas.height);c.scale(this.canvas.width/VW,this.canvas.height/VH);const sx=this.shake*(Math.random()-.5)*8,sy=this.shake*(Math.random()-.5)*8;c.translate(sx,sy);this.drawBackground(c);this.drawPlatforms(c);this.drawSetPieces(c);this.drawEnemies(c);this.drawPlayer(c);this.drawLantern(c);this.drawParticles(c);this.drawOverlay(c);c.restore();}
 private drawBackground(c:CanvasRenderingContext2D){const act=actAt(this.player.x);const top=act==='FEAR'?'#07131d':act==='DOUBT'?'#120d20':'#0b0716',bot=act==='FEAR'?'#10232d':act==='DOUBT'?'#32173b':'#35123d';const g=c.createLinearGradient(0,0,0,VH);g.addColorStop(0,top);g.addColorStop(1,bot);c.fillStyle=g;c.fillRect(0,0,VW,VH);for(let i=0;i<20;i++){const x=(i*170-this.camera.x*.08)%1500;c.fillStyle=act==='IDENTITY'?'#25112e':'#162d37';c.fillRect(x,350-(i%3)*35,80+(i%4)*25,250);}c.fillStyle='#c7e8e6';c.beginPath();c.arc(1000-this.camera.x*.03,90,36,0,Math.PI*2);c.fill();}
 private drawPlatforms(c:CanvasRenderingContext2D){const a=this.camera.x-100,b=this.camera.x+VW+100;for(const s of platforms){if(s.x+s.w<a||s.x>b)continue;const x=s.x-this.camera.x;c.fillStyle=s.material==='water'?'#173b40':s.material==='wood'?'#3a2e2b':'#202b32';c.fillRect(x,s.y,s.w,s.h);c.fillStyle=s.moss?'#59634e':'#34414a';c.fillRect(x,s.y,s.w,7);}}
 private drawSetPieces(c:CanvasRenderingContext2D){const x=this.player.x;if(x>5300&&x<6680){for(let i=0;i<24;i++){const qx=5360+i*60-this.camera.x,qy=610-(i%4)*50;c.globalAlpha=this.memoryMode?.75:.18;c.strokeStyle='#8ee1d2';c.beginPath();c.arc(qx,qy,9,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(qx,qy);c.lineTo(qx,qy-35);c.stroke();}c.globalAlpha=1;}if(x>6680&&x<8400){for(let i=0;i<16;i++){const qx=6720+i*110-this.camera.x,qy=300+(i%4)*75;c.globalAlpha=this.memoryMode?.75:.28;c.fillStyle='#bfece0';c.fillRect(qx,qy,48,68);c.fillStyle='#e7d4b2';c.fillRect(qx+8,qy+13,28,2);c.fillRect(qx+8,qy+26,23,2);}c.globalAlpha=1;}if(x>8400&&x<9740){const qx=this.player.x+220-this.camera.x;c.globalAlpha=.18;c.strokeStyle='#c58ad7';c.lineWidth=5;c.strokeRect(qx,160,250,430);c.globalAlpha=1;}}
 private drawEnemies(c:CanvasRenderingContext2D){for(const e of this.enemies){if(e.dead)continue;const x=e.x-this.camera.x,y=e.y;c.save();if(e.hitFlash>0)c.globalAlpha=.45;if(e.kind==='hollow'){c.fillStyle='#111722';c.beginPath();c.ellipse(x+19,y+34,20,29,0,0,Math.PI*2);c.fill();c.fillStyle='#d56b46';c.beginPath();c.arc(x+27,y+25,4,0,Math.PI*2);c.fill();}else if(e.kind==='skitter'){c.fillStyle='#14131d';c.beginPath();c.ellipse(x+26,y+17,27,16,0,0,Math.PI*2);c.fill();for(let i=0;i<4;i++){c.strokeStyle='#363047';c.beginPath();c.moveTo(x+8+i*12,y+20);c.lineTo(x-5+i*8,y+34);c.stroke();}}else if(e.kind==='watcher'){c.fillStyle=e.x>8200?'#26152f':'#141923';c.beginPath();c.moveTo(x+24,y);c.lineTo(x+48,y+54);c.lineTo(x+30,y+64);c.lineTo(x+6,y+54);c.closePath();c.fill();c.fillStyle='#e6a06d';c.beginPath();c.arc(x+25,y+26,5,0,Math.PI*2);c.fill();}else if(e.kind==='warden'&&e.x>10000){c.fillStyle='#100b17';for(let i=0;i<7;i++){c.beginPath();c.moveTo(x+55,y+20);c.quadraticCurveTo(x-20+i*25,y+95,x-30+i*28,y+155);c.lineTo(x+55,y+155);c.fill();}c.strokeStyle='#a27bb7';c.lineWidth=3;c.strokeRect(x+25,y+25,60,48);c.fillStyle='#f0b65c';c.beginPath();c.arc(x+55,y+48,8,0,Math.PI*2);c.fill();}else if(e.kind==='warden'&&e.x>6800){c.fillStyle='#15171d';c.beginPath();c.moveTo(x+55,y+5);c.lineTo(x+105,y+40);c.lineTo(x+96,y+145);c.lineTo(x+12,y+145);c.lineTo(x+5,y+40);c.closePath();c.fill();c.strokeStyle='#79b7b3';c.lineWidth=3;c.stroke();for(let i=0;i<4;i++){c.beginPath();c.moveTo(x+15+i*24,y+20);c.lineTo(x+90-i*18,y+120);c.stroke();}c.fillStyle='#bce8df';c.fillRect(x+45,y+55,20,8);}else if(e.kind==='warden'){c.fillStyle='#171520';c.fillRect(x+20,y+20,e.w-40,e.h-20);c.strokeStyle='#8b6b57';c.lineWidth=5;c.strokeRect(x+18,y+18,e.w-36,e.h-28);c.fillStyle='#f0b65c';c.beginPath();c.arc(x+e.w/2,y+52,12,0,Math.PI*2);c.fill();}else{c.fillStyle='#100817';for(let i=0;i<7;i++){c.beginPath();c.moveTo(x+e.w/2,y+35);c.quadraticCurveTo(x-30+i*30,y+100,x-50+i*40,y+e.h);c.lineTo(x+e.w/2,y+e.h);c.fill();}c.fillStyle='#ffb85e';c.beginPath();c.arc(x+e.w/2,y+35,13,0,Math.PI*2);c.fill();c.fillStyle='#fff1bb';c.beginPath();c.arc(x+e.w/2,y+35,5,0,Math.PI*2);c.fill();}c.restore();}}
 private drawPlayer(c:CanvasRenderingContext2D){const p=this.player,x=p.x-this.camera.x,y=p.y;c.fillStyle='rgba(255,190,80,.18)';c.beginPath();c.arc(x+17,y+32,60,0,Math.PI*2);c.fill();c.fillStyle='#0c1118';c.beginPath();c.moveTo(x+17,y);c.quadraticCurveTo(x+43,y+4,x+38,y+34);c.quadraticCurveTo(x+35,y+48,x+50,y+58);c.lineTo(x-2,y+58);c.quadraticCurveTo(x+8,y+42,x-1,y+31);c.quadraticCurveTo(x-7,y+5,x+17,y);c.fill();c.strokeStyle='#8fb6bf';c.stroke();c.fillStyle='#f8e8b1';c.beginPath();c.ellipse(x+11,y+27,5,8,0,0,Math.PI*2);c.ellipse(x+25,y+27,5,8,0,0,Math.PI*2);c.fill();c.fillStyle='#f3ad4e';c.beginPath();c.arc(x+18,y+43,10,0,Math.PI*2);c.fill();if(this.ghostVisible()){c.globalAlpha=.18;c.strokeStyle='#c58ad7';c.strokeRect(x+150,y+10,30,54);c.globalAlpha=1;}}
 private drawLantern(c:CanvasRenderingContext2D){const x=this.player.x+31-this.camera.x,y=this.player.y+24+Math.sin(this.time*3)*3;const g=c.createRadialGradient(x,y,2,x,y,75);g.addColorStop(0,'rgba(255,201,94,.68)');g.addColorStop(1,'rgba(255,201,94,0)');c.fillStyle=g;c.fillRect(x-95,y-95,190,190);c.strokeStyle='#c58a3e';c.lineWidth=3;c.beginPath();c.arc(x,y,10,0,Math.PI*2);c.stroke();c.fillStyle='#ffd37a';c.beginPath();c.arc(x,y,6,0,Math.PI*2);c.fill();if(this.lanternThrown){c.strokeStyle='#f4c76d';c.beginPath();c.arc(this.lanternX-this.camera.x,this.lanternY,11,0,Math.PI*2);c.stroke();}}
 private drawParticles(c:CanvasRenderingContext2D){for(const q of this.particles){c.globalAlpha=clamp(q.life/q.maxLife,0,1);c.fillStyle=q.color;c.beginPath();c.arc(q.x-this.camera.x,q.y,q.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 private drawOverlay(c:CanvasRenderingContext2D){const darkness=clamp(.24+(.55-this.player.lantern/200)+(actAt(this.player.x)==='IDENTITY'?.1:0),.2,.76);c.fillStyle=`rgba(2,5,10,${darkness})`;c.fillRect(0,0,VW,VH);const vign=c.createRadialGradient(VW/2,VH/2,170,VW/2,VH/2,700);vign.addColorStop(0,'rgba(0,0,0,0)');vign.addColorStop(1,'rgba(0,0,0,.62)');c.fillStyle=vign;c.fillRect(0,0,VW,VH);if(this.memoryMode){c.fillStyle='rgba(120,230,215,.07)';c.fillRect(0,0,VW,VH);}if(this.pulse>0){const x=this.player.x+17-this.camera.x,y=this.player.y+28;c.strokeStyle=`rgba(255,213,120,${this.pulse*.55})`;c.lineWidth=3;c.beginPath();c.arc(x,y,180+(1-this.pulse)*180,0,Math.PI*2);c.stroke();}if(this.horror>0){c.fillStyle=`rgba(80,0,70,${this.horror*.08})`;c.fillRect(0,0,VW,VH);}if(this.redFlash>0){c.fillStyle=`rgba(255,50,40,${this.redFlash*.16})`;c.fillRect(0,0,VW,VH);}}
}
