import { areaAt, checkpoints, platforms, WORLD_HEIGHT, WORLD_WIDTH } from './level';
import type { AreaId, Enemy, GameSettings, GameSnapshot, InputState, Particle, Player } from './types';

const VW = 1280, VH = 720;
const clamp = (v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp = (a:number,b:number,t:number)=>a+(b-a)*t;
const hit=(a:{x:number;y:number;w:number;h:number},b:{x:number;y:number;w:number;h:number})=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;

type Mode='title'|'playing'|'paused'|'ending';
type LanternMode='ILLUMINATE'|'REVEAL'|'PULSE'|'MEMORY'|'PURITY';

const beats:Array<[string,string,number]>=[
 ['THE FIRST WAKING','The lantern is warm. Someone was holding it before you.',0],
 ['THE HOLLOW','A bell rope sways without wind. The keeper left in a hurry.',720],
 ['THE DARK CAVE','Light is not only for seeing. Some things fear being remembered.',1580],
 ['THE MEMORY ROOM','For eight seconds, the dead city remembers how to breathe.',2740],
 ['THE BELL WARDEN','You should not have remembered that.',3920],
 ['THE THRESHOLD','What is real if memories can lie?',5300],
 ['THE MEMORY GARDEN','Every flower disappears when you stop remembering it.',6100],
 ['THE ARCHIVE','Every name here belongs to someone who thought they were the hero.',6840],
 ['THE MIRROR WARD','Your reflection is late. Do not wait for it to catch up.',8400],
 ['THE KEEPER','I was not protecting the Hollow from you. I was protecting you from the Hollow.',10160],
 ['THE EATER','I am not your enemy. I am everything you refused to remember.',10800],
] as const;

const newPlayer=():Player=>({x:150,y:560,w:34,h:58,vx:0,vy:0,facing:1,grounded:false,coyote:0,jumpBuffer:0,dashTimer:0,dashCooldown:0,attackTimer:0,attackCooldown:0,burstTimer:0,burstCooldown:0,veilTimer:0,veilCooldown:0,health:4,maxHealth:4,lantern:100,maxLantern:100,invuln:0,hurtFlash:0,landTimer:0,runTime:0,hurtTimer:0});

function cloneEnemies():Enemy[]{return [
 {id:1,kind:'hollow',x:1020,y:540,w:38,h:60,vx:0,vy:0,hp:3,maxHp:3,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:0},
 {id:2,kind:'skitter',x:1390,y:640,w:52,h:34,vx:0,vy:0,hp:3,maxHp:3,grounded:false,hitFlash:0,alert:0,attackTimer:.8,attackWindup:0,dead:false,phase:.4},
 {id:3,kind:'hollow',x:1730,y:535,w:38,h:60,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:1},
 {id:4,kind:'watcher',x:2350,y:555,w:48,h:64,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:2},
 {id:5,kind:'hollow',x:3040,y:600,w:38,h:60,vx:0,vy:0,hp:6,maxHp:6,grounded:false,hitFlash:0,alert:0,attackTimer:1.2,attackWindup:0,dead:false,phase:3},
 {id:6,kind:'warden',x:4050,y:475,w:104,h:155,vx:0,vy:0,hp:16,maxHp:16,grounded:false,hitFlash:0,alert:0,attackTimer:2,attackWindup:0,dead:false,phase:1},
 {id:7,kind:'skitter',x:4880,y:605,w:52,h:34,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:0},
 {id:8,kind:'watcher',x:6120,y:500,w:48,h:64,vx:0,vy:0,hp:6,maxHp:6,grounded:false,hitFlash:0,alert:0,attackTimer:1.5,attackWindup:0,dead:false,phase:0},
 {id:10,kind:'watcher',x:7280,y:505,w:48,h:64,vx:0,vy:0,hp:7,maxHp:7,grounded:false,hitFlash:0,alert:0,attackTimer:1.5,attackWindup:0,dead:false,phase:.8},
 {id:11,kind:'hollow',x:7900,y:570,w:38,h:60,vx:0,vy:0,hp:7,maxHp:7,grounded:false,hitFlash:0,alert:0,attackTimer:1.1,attackWindup:0,dead:false,phase:1.4},
 {id:12,kind:'watcher',x:8540,y:510,w:48,h:64,vx:0,vy:0,hp:8,maxHp:8,grounded:false,hitFlash:0,alert:0,attackTimer:1.3,attackWindup:0,dead:false,phase:2.1},
 {id:13,kind:'skitter',x:9280,y:575,w:52,h:34,vx:0,vy:0,hp:8,maxHp:8,grounded:false,hitFlash:0,alert:0,attackTimer:.9,attackWindup:0,dead:false,phase:2.8},
 {id:14,kind:'hollow',x:10020,y:615,w:38,h:60,vx:0,vy:0,hp:9,maxHp:9,grounded:false,hitFlash:0,alert:0,attackTimer:1.6,attackWindup:0,dead:false,phase:3.4},
 {id:15,kind:'warden',x:10360,y:410,w:104,h:155,vx:0,vy:0,hp:12,maxHp:12,grounded:false,hitFlash:0,alert:0,attackTimer:2.2,attackWindup:0,dead:false,phase:3.9},
 {id:9,kind:'eater',x:10920,y:490,w:150,h:165,vx:0,vy:0,hp:28,maxHp:28,grounded:false,hitFlash:0,alert:0,attackTimer:2,attackWindup:0,dead:false,phase:1},
 ];}

export class FlikkerEngine {
 canvas:HTMLCanvasElement; ctx:CanvasRenderingContext2D; player=newPlayer(); enemies:Enemy[]=cloneEnemies(); particles:Particle[]=[];
 input:InputState={left:false,right:false,jump:false,dash:false,attack:false,burst:false,pause:false,special:false};
 settings:GameSettings={reducedFlicker:false,screenShake:true,brightness:1,volume:.42,touchControls:true};
 mode:Mode='title'; camera={x:0,shake:0}; time=0; last=0; checkpoint=0; bossDefeated=false;
 toast='The light remembers the way'; toastTimer=3; storyBeat=0; storyKicker=beats[0][0]; storyLine=beats[0][1]; storyTimer=0;
 lanternMode:LanternMode='ILLUMINATE'; memoryMode=false; pulse=0; lanternThrown=0; lanternX=0; lanternY=0; lanternReturn=false;
 combo=0; comboWindow=0; hitStop=0; shake=0; horror=0; redFlash=0; endingTimer=0; lastArea:AreaId='THE THRESHOLD';
 onSnapshot:(s:GameSnapshot)=>void=()=>{}; private raf=0; private audioCtx:AudioContext|null=null;

 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable');this.ctx=c;this.resize();}
 start(){this.resize();window.addEventListener('resize',this.resize);window.addEventListener('keydown',this.key);this.raf=requestAnimationFrame(this.loop);}
 destroy(){window.removeEventListener('resize',this.resize);window.removeEventListener('keydown',this.key);cancelAnimationFrame(this.raf);}
 resize=()=>{const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(this.canvas.clientWidth*d));this.canvas.height=Math.max(1,Math.floor(this.canvas.clientHeight*d));};
 setSettings(s:GameSettings){this.settings=s;}
 setInput(i:Partial<InputState>){this.input={...this.input,...i};}
 touchAction(a:keyof InputState,p=true){if(a==='pause'){this.mode=this.mode==='paused'?'playing':'paused';return;}this.setInput({[a]:p});}
 setMode(m:Mode){this.mode=m;}
 begin(){this.ensureAudio();this.mode='playing';this.player=newPlayer();this.enemies=cloneEnemies();this.particles=[];this.checkpoint=0;checkpoints.forEach(c=>c.activated=false);this.bossDefeated=false;this.camera.x=0;this.time=0;this.lanternMode='ILLUMINATE';this.memoryMode=false;this.pulse=0;this.toast='THE LIGHT REMEMBERS';this.toastTimer=2.5;this.storyBeat=0;this.storyKicker=beats[0][0];this.storyLine=beats[0][1];this.storyTimer=4.8;this.lastArea='THE THRESHOLD';this.endingTimer=0;this.onSnapshot(this.getSnapshot());}
 private ensureAudio(){try{if(!this.audioCtx)this.audioCtx=new AudioContext();if(this.audioCtx.state==='suspended')void this.audioCtx.resume();}catch{}}
 private beep(freq:number,d=.08){try{if(!this.audioCtx)return;const o=this.audioCtx.createOscillator(),g=this.audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.0001,this.audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,this.audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,this.audioCtx.currentTime+d);o.connect(g);g.connect(this.audioCtx.destination);o.start();o.stop(this.audioCtx.currentTime+d+.02);}catch{}}
 private key=(e:KeyboardEvent)=>{if(this.mode!=='playing')return;if(e.code==='KeyQ'&&!e.repeat){this.cycleLantern();e.preventDefault();}if(e.code==='KeyL'&&!e.repeat){this.useLanternAbility();e.preventDefault();}if(e.code==='KeyR'&&!e.repeat){this.recallLantern();e.preventDefault();}if(e.code==='KeyE'&&!e.repeat){this.useLanternAbility();e.preventDefault();}};
 private cycleLantern(){const modes:LanternMode[]=['ILLUMINATE','REVEAL','PULSE','MEMORY','PURITY'];this.lanternMode=modes[(modes.indexOf(this.lanternMode)+1)%modes.length];this.toast=this.lanternMode;this.toastTimer=.8;this.beep(420);}
 private useLanternAbility(){if(this.player.lantern<8)return;this.player.lantern-=8;switch(this.lanternMode){case'ILLUMINATE':this.pulse=.9;break;case'REVEAL':this.pulse=1.5;break;case'PULSE':this.pulse=1.2;this.revealEnemies(420);break;case'MEMORY':this.memoryMode=!this.memoryMode;this.toast=this.memoryMode?'MEMORY / PAST':'PRESENT / RUIN';this.toastTimer=1.4;break;case'PURITY':this.pulse=1;this.revealEnemies(520);for(const e of this.enemies)if(!e.dead&&e.alert>0)e.vulnerable=true;break;}this.beep(620,.12);}
 private recallLantern(){if(this.lanternThrown<=0){this.lanternThrown=1;this.lanternX=this.player.x+this.player.facing*110;this.lanternY=this.player.y+25;this.toast='LANTERN THROW';this.toastTimer=.7;}else this.lanternReturn=true;}
 getSnapshot():GameSnapshot{const boss=this.currentBoss();const g=this.ghost();return{mode:this.mode,area:areaAt(this.player.x),lantern:this.player.lantern,health:this.player.health,bossHealth:boss?.hp??0,bossMaxHealth:boss?.maxHp??0,checkpoint:this.checkpoint,toast:this.toastTimer>0?this.toast:'',storyKicker:this.storyKicker,storyLine:this.storyLine,storyTimer:this.storyTimer,storyBeat:this.storyBeat,ghostVisible:g.visible,ghostGesture:g.gesture,progress:clamp(this.player.x/(WORLD_WIDTH-500),0,1)};}
 private currentBoss(){return this.enemies.find(e=>(e.kind==='eater'||e.kind==='warden')&&!e.dead);}
 private ghost(){const late=this.player.x>7600;const visible=late&&Math.sin(this.time*1.7)>0.72;return{visible,gesture:(visible?(this.player.x>9500?'watch':'point'):'wait') as 'wait'|'point'|'watch'|'vanish'};}
 private loop=(now:number)=>{const dt=Math.min((now-this.last)/1000||.016,.033);this.last=now;this.time+=dt;if(this.mode==='playing')this.update(dt);this.render();this.raf=requestAnimationFrame(this.loop);};
 private update(dt:number){if(this.hitStop>0){this.hitStop-=dt;this.updateParticles(dt);return;}const p=this.player;
  p.coyote=p.grounded?.12:Math.max(0,p.coyote-dt);p.jumpBuffer=this.input.jump?.12:Math.max(0,p.jumpBuffer-dt);p.dashCooldown=Math.max(0,p.dashCooldown-dt);p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.burstCooldown=Math.max(0,p.burstCooldown-dt);p.attackTimer=Math.max(0,p.attackTimer-dt);p.burstTimer=Math.max(0,p.burstTimer-dt);p.invuln=Math.max(0,p.invuln-dt);p.hurtFlash=Math.max(0,p.hurtFlash-dt);p.landTimer=Math.max(0,(p.landTimer||0)-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);this.toastTimer=Math.max(0,this.toastTimer-dt);this.storyTimer=Math.max(0,this.storyTimer-dt);this.pulse=Math.max(0,this.pulse-dt);this.horror=Math.max(0,this.horror-dt*.4);this.redFlash=Math.max(0,this.redFlash-dt*3);
  this.updateStory();
  if(this.input.jump&&p.jumpBuffer>0&&(p.grounded||p.coyote>0||p.veilTimer>0)){p.vy=-680;p.grounded=false;p.coyote=0;p.jumpBuffer=0;this.beep(280);this.spawnBurst(p.x+17,p.y+p.h,8,'#dbe6dd');}
  const dir=(this.input.right?1:0)-(this.input.left?1:0);if(dir){p.facing=dir;p.vx=lerp(p.vx,dir*310,Math.min(1,dt*12));p.runTime=(p.runTime||0)+dt;}else{p.vx=lerp(p.vx,0,Math.min(1,dt*10));p.runTime=0;}
  if(this.input.dash&&p.dashCooldown<=0){p.dashTimer=.18;p.dashCooldown=.85;p.vx=p.facing*760;p.vy=0;p.invuln=.25;this.beep(180);this.spawnBurst(p.x,p.y+25,14,'#f2d38d');}
  if(p.dashTimer>0){p.dashTimer-=dt;p.vx=p.facing*760;p.vy=0;}else p.vy+=1700*dt;
  if(this.input.attack&&p.attackCooldown<=0)this.attack();
  if(this.input.burst&&p.burstCooldown<=0&&p.lantern>=15){p.burstCooldown=1.1;p.burstTimer=.5;p.lantern-=15;this.pulse=.8;this.revealEnemies(360);this.spawnBurst(p.x+17,p.y+28,32,'#ffd77b');this.beep(760,.15);}
  this.updateLantern(dt);this.updateLanternThrow(dt);
  const oldX=p.x,oldY=p.y;p.x=clamp(p.x+p.vx*dt,-30,WORLD_WIDTH-p.w-20);this.horizontal(p,oldX,platforms);p.y+=p.vy*dt;p.grounded=false;this.vertical(p,oldY,platforms);
  if(!p.grounded&&p.vy>80&&dir&&this.nearWall(p)){p.vy=Math.min(p.vy,140);p.veilTimer=.05;}
  if(p.y>WORLD_HEIGHT+100)this.respawn();
  this.updateEnemies(dt);this.updateParticles(dt);this.updateCheckpoints();
  const a=areaAt(p.x);if(a!==this.lastArea){this.lastArea=a;this.toast=a;this.toastTimer=2.2;this.spawnBurst(p.x,p.y,18,'#e8bd67');}
  const eater=this.enemies.find(e=>e.kind==='eater');if(eater?.dead&&!this.bossDefeated){this.bossDefeated=true;this.storyKicker='THE LIGHT REMEMBERS';this.storyLine='I am not your enemy. I am everything you refused to remember.';this.storyTimer=6;this.toast='THE FLIKKER';this.toastTimer=4;this.endingTimer=6;}
  if(this.bossDefeated){this.endingTimer-=dt;if(this.endingTimer<=0)this.mode='ending';}
  this.camera.x=lerp(this.camera.x,clamp(p.x-VW*.42,0,WORLD_WIDTH-VW),Math.min(1,dt*4.5));this.camera.shake=this.settings.screenShake?this.shake:0;this.shake=Math.max(0,this.shake-dt*4);
  this.input.jump=false;this.input.dash=false;this.input.attack=false;this.input.burst=false;this.input.special=false;
 }
 private updateStory(){const x=this.player.x;for(let i=beats.length-1;i>=0;i--){if(x>=beats[i][2]&&i>=this.storyBeat){this.storyBeat=i;this.storyKicker=beats[i][0];this.storyLine=beats[i][1];this.storyTimer=4.2;this.toast=beats[i][0];this.toastTimer=2.2;break;}}}
 private updateLantern(dt:number){const natural=this.player.x<1200||this.player.x>2600&&this.player.x<3400||this.player.x>6000&&this.player.x<6800;const drain=.28+(this.player.x>7600?.18:0);this.player.lantern=clamp(this.player.lantern+(natural?.9:0)-drain*dt,0,this.player.maxLantern);if(this.player.lantern<18){this.horror=.7;if(this.toastTimer<=0){this.toast='THE DARK HAS FOUND YOU';this.toastTimer=1.2;}}}
 private updateLanternThrow(dt:number){if(this.lanternThrown<=0)return;const target=this.lanternReturn?this.player.x+17:this.lanternX+this.player.facing*360*dt;this.lanternX=this.lanternReturn?lerp(this.lanternX,target,Math.min(1,dt*7)):target;this.lanternY=lerp(this.lanternY,this.player.y+24,.08);if(this.lanternReturn&&Math.abs(this.lanternX-(this.player.x+17))<25){this.lanternThrown=0;this.lanternReturn=false;this.toast='LANTERN RETURN';this.toastTimer=.7;}}
 private revealEnemies(r:number){for(const e of this.enemies)if(!e.dead&&Math.hypot(this.player.x-e.x,this.player.y-e.y)<r){e.alert=1;e.vulnerable=true;}}
 private attack(){const p=this.player;if(this.comboWindow<=0)this.combo=0;this.combo=this.combo%3+1;this.comboWindow=.48;p.attackTimer=.24;p.attackCooldown=.2;const range=this.combo===3?110:82;const hb={x:p.facing>0?p.x+8:p.x-range+28,y:p.y+(this.combo===3?-12:8),w:range,h:this.combo===3?76:54};for(const e of this.enemies){if(e.dead||!hit(hb,e)||((e.kind==='warden'||e.kind==='eater')&&!e.vulnerable))continue;let dmg=this.combo===3?3:1;if(this.lanternMode==='PURITY')dmg+=1;e.hp-=dmg;e.hitFlash=.18;e.vx=p.facing*(260+this.combo*70);e.vy=this.combo===3?-430:-210;this.hitStop=.06;this.shake=.18;this.spawnBurst(e.x+e.w/2,e.y+e.h/2,10,'#ffe2a0');if(e.hp<=0){e.dead=true;this.spawnBurst(e.x+e.w/2,e.y+e.h/2,32,'#ffd36f');}}
  this.toast=this.combo===3?'FALLING STAR':this.combo===2?'RISING LIGHT':'SPARK';this.toastTimer=.35;this.beep(360+this.combo*90);}
 private horizontal(b:{x:number;y:number;w:number;h:number;vx:number},oldX:number,surfaces:Platform[]){if(!b.vx)return;for(const s of surfaces){if(s.oneWay)continue;const y=s.y;if(b.y+b.h<=y+5||b.y>=y+s.h)continue;if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX+b.w<=s.x&&b.vx>0){b.x=s.x-b.w-.01;b.vx=0;}else if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX>=s.x+s.w&&b.vx<0){b.x=s.x+s.w+.01;b.vx=0;}}}
 private vertical(b:{x:number;y:number;w:number;h:number;vy:number;grounded:boolean},oldY:number,surfaces:Platform[]){if(b.vy<0)return;let land:Platform|undefined;for(const s of surfaces){const crossed=oldY+b.h<=s.y+4&&b.y+b.h>=s.y;if(crossed&&b.x+b.w>s.x+3&&b.x<s.x+s.w-3&&(!s.oneWay||oldY+b.h<=s.y+2)&&(!land||s.y<land.y))land=s;}if(land){b.y=land.y-b.h;b.vy=0;b.grounded=true;}}
 private nearWall(p:Player){return platforms.some(s=>p.y+p.h>s.y+5&&p.y<s.y+s.h&&((Math.abs(p.x+p.w-s.x)<10)||(Math.abs(p.x-(s.x+s.w))<10)));}
 private updateEnemies(dt:number){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer-=dt;e.alert=Math.max(0,e.alert-dt*.35);const d=p.x-e.x;const dist=Math.abs(d);const late=e.x>7600;const boss=e.kind==='warden'||e.kind==='eater';if(boss){e.phase=(e.phase||1)+dt*.35;this.bossAttack(e,dt);continue;}if(e.kind==='watcher'&&late){e.vx=dist<420?Math.sign(d)*35:0;e.y+=Math.sin(this.time*1.8+(e.id||0))*.25;continue;}if(dist<430||e.alert>0){e.vx=Math.sign(d)*((e.kind==='skitter'?115:70)+(late?25:0));if(e.attackTimer<=0&&dist<85){e.attackTimer=e.kind==='skitter'?.9:1.35;this.damagePlayer(e.kind==='skitter'?9:7);}}else e.vx=Math.sin(this.time+(e.id||0))*12;e.x+=e.vx*dt;this.enemyGround(e);}}
 private enemyGround(e:Enemy){let land=platforms.find(s=>e.x+e.w>s.x&&e.x<s.x+s.w&&Math.abs(e.y+e.h-s.y)<12);if(land)e.y=land.y-e.h;}
 private bossAttack(e:Enemy,dt:number){e.attackTimer-=dt;if(e.attackTimer>0)return;const p=this.player;const phase=Math.floor((e.phase||1))%4;e.attackTimer=e.kind==='eater'?.9:1.25;if(phase===0){this.damagePlayer(10);}else if(phase===1){if(Math.abs(p.x-e.x)<520)this.damagePlayer(7);this.spawnBurst(e.x+e.w/2,e.y+70,18,'#b66b8f');}else if(phase===2){this.pulse=.7;this.horror=.8;this.spawnBurst(p.x+17,p.y+28,20,'#8b6bc9');}else{e.vulnerable=true;this.toast=e.kind==='eater'?'THE VOID IS OPEN':'RING THE MEMORY';this.toastTimer=.8;}}
 private damagePlayer(amount:number){const p=this.player;if(p.invuln>0)return;p.health=clamp(p.health-amount,0,p.maxHealth);p.hurtFlash=.25;p.invuln=.45;this.redFlash=.5;this.shake=.4;this.beep(110);if(p.health<=0)this.respawn();}
 private updateCheckpoints(){for(let i=0;i<checkpoints.length;i++){const c=checkpoints[i];if(!c.activated&&this.player.x>=c.x){c.activated=true;this.checkpoint=i;this.player.health=this.player.maxHealth;this.player.lantern=this.player.maxLantern;this.toast='LUMEN SHRINE';this.toastTimer=1.2;this.spawnBurst(c.x,c.y-20,22,'#f4cf76');}}}
 private respawn(){const c=checkpoints[this.checkpoint]||checkpoints[0];this.player.x=c.x;this.player.y=c.y-this.player.h-5;this.player.vx=0;this.player.vy=0;this.player.health=this.player.maxHealth;this.player.lantern=Math.max(55,this.player.maxLantern);this.redFlash=0;this.horror=0;this.toast='THE LANTERN BRINGS YOU BACK';this.toastTimer=1.8;}
 private spawnBurst(x:number,y:number,n:number,color:string){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*170;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.55,maxLife:.9,size:1+Math.random()*3,color,gravity:40});}}
 private updateParticles(dt:number){for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=(q.gravity||0)*dt;}this.particles=this.particles.filter(q=>q.life>0);}
 private worldToScreen(x:number,y:number){return{x:x-this.camera.x,y};}
 private render(){const c=this.ctx;c.save();const sx=this.shake*(Math.random()-.5)*8,sy=this.shake*(Math.random()-.5)*8;c.clearRect(0,0,this.canvas.width,this.canvas.height);const scaleX=this.canvas.width/VW,scaleY=this.canvas.height/VH;c.scale(scaleX,scaleY);c.translate(sx,sy);this.drawSky(c);this.drawWorld(c);this.drawMemoryWorld(c);this.drawParticles(c);this.drawEnemies(c);this.drawPlayer(c);this.drawLantern(c);this.drawAtmosphere(c);c.restore();}
 private drawSky(c:CanvasRenderingContext2D){const x=this.player.x;let top='#07131d',bottom='#10232d';if(x>5200){top='#160e22';bottom='#29132f';}if(x>7600){top='#0f0a1b';bottom='#32153b';}if(x>10300){top='#09050f';bottom='#17081e';}const g=c.createLinearGradient(0,0,0,VH);g.addColorStop(0,top);g.addColorStop(1,bottom);c.fillStyle=g;c.fillRect(0,0,VW,VH);c.globalAlpha=.55;for(let i=0;i<28;i++){const px=(i*157-(this.camera.x*.12))%1500;const py=60+(i*83)%360;c.fillStyle=i%3?'#243746':'#6d6a55';c.fillRect(px,py,2+(i%3),80+(i%5)*30);}c.globalAlpha=1;const moonX=990-this.camera.x*.04;c.fillStyle='#c7e8e6';c.beginPath();c.arc(moonX,90,38,0,Math.PI*2);c.fill();c.fillStyle=top;c.beginPath();c.arc(moonX+15,80,35,0,Math.PI*2);c.fill();}
 private drawWorld(c:CanvasRenderingContext2D){const start=Math.max(0,this.camera.x-100),end=this.camera.x+VW+100;for(const s of platforms){if(s.x+s.w<start||s.x>end)continue;const {x,y}=this.worldToScreen(s.x,s.y);c.fillStyle=s.material==='water'?'#18363b':s.material==='wood'?'#3a302b':'#202b32';c.fillRect(x,y,s.w,s.h);c.fillStyle=s.moss?'#59634e':'#34414a';c.fillRect(x,y,s.w,7);if(s.moss){c.globalAlpha=.55;for(let i=0;i<Math.floor(s.w/40);i++){c.fillStyle='#a6b47c';c.fillRect(x+i*40+8,y-4-(i%2)*3,2,7);}c.globalAlpha=1;}}
  for(let i=0;i<18;i++){const wx=400+i*620;const x=wx-this.camera.x;if(x<-180||x>VW+180)continue;c.strokeStyle=i%2?'#1d303a':'#243c48';c.lineWidth=18;c.beginPath();c.moveTo(x,560);c.lineTo(x,260+(i%3)*40);c.quadraticCurveTo(x+80,180+(i%3)*20,x+160,260+(i%3)*40);c.lineTo(x+160,560);c.stroke();c.fillStyle='#d99b45';c.beginPath();c.arc(x+80,285+(i%3)*40,4,0,Math.PI*2);c.fill();}}
 private drawMemoryWorld(c:CanvasRenderingContext2D){if(!this.memoryMode)return;const x0=this.camera.x;for(let i=0;i<12;i++){const wx=550+i*430;const x=wx-x0;if(x<-100||x>VW+100)continue;c.globalAlpha=.32;c.fillStyle='#9de1e0';c.fillRect(x,430-(i%3)*60,150,14);c.globalAlpha=1;c.fillStyle='#d5f4e7';c.fillRect(x+10,425-(i%3)*60,3,4);}c.fillStyle='rgba(130,220,205,.08)';c.fillRect(0,0,VW,VH);}
 private drawParticles(c:CanvasRenderingContext2D){for(const q of this.particles){const p=this.worldToScreen(q.x,q.y);c.globalAlpha=clamp(q.life/q.maxLife,0,1);c.fillStyle=q.color;c.beginPath();c.arc(p.x,p.y,q.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 private drawEnemies(c:CanvasRenderingContext2D){for(const e of this.enemies){if(e.dead)continue;const p=this.worldToScreen(e.x,e.y);const boss=e.kind==='warden'||e.kind==='eater';c.save();if(e.hitFlash>0)c.globalAlpha=.45;if(e.kind==='hollow'){c.fillStyle='#111722';c.beginPath();c.ellipse(p.x+19,p.y+34,20,29,0,0,Math.PI*2);c.fill();c.fillStyle='#d56b46';c.beginPath();c.arc(p.x+27,p.y+25,4,0,Math.PI*2);c.fill();}else if(e.kind==='skitter'){c.fillStyle='#14131d';c.beginPath();c.ellipse(p.x+26,p.y+17,27,16,0,0,Math.PI*2);c.fill();for(let i=0;i<4;i++){c.strokeStyle='#363047';c.beginPath();c.moveTo(p.x+8+i*12,p.y+20);c.lineTo(p.x-5+i*8,p.y+34);c.stroke();}c.fillStyle='#e08a4e';c.beginPath();c.arc(p.x+31,p.y+13,3,0,Math.PI*2);c.fill();}else if(e.kind==='watcher'){c.fillStyle=lateColor(this.player.x);c.beginPath();c.moveTo(p.x+24,p.y);c.lineTo(p.x+48,p.y+54);c.lineTo(p.x+30,p.y+64);c.lineTo(p.x+6,p.y+54);c.closePath();c.fill();c.fillStyle='#e6a06d';c.beginPath();c.arc(p.x+25,p.y+26,5,0,Math.PI*2);c.fill();}else if(e.kind==='warden'){c.fillStyle='#171520';c.fillRect(p.x+20,p.y+20,e.w-40,e.h-20);c.strokeStyle='#8b6b57';c.lineWidth=5;c.strokeRect(p.x+18,p.y+18,e.w-36,e.h-28);c.fillStyle='#f0b65c';c.beginPath();c.arc(p.x+e.w/2,p.y+52,12,0,Math.PI*2);c.fill();c.strokeStyle='#d7b06b';c.lineWidth=4;c.beginPath();c.arc(p.x+e.w/2,p.y+40,28,Math.PI,Math.PI*2);c.stroke();if(boss){c.globalAlpha=.18+.12*Math.sin(this.time*5);c.fillStyle='#c27a6a';c.beginPath();c.arc(p.x+e.w/2,p.y+70,85,0,Math.PI*2);c.fill();c.globalAlpha=1;}}else{c.fillStyle='#100817';for(let i=0;i<7;i++){c.beginPath();c.moveTo(p.x+e.w/2,p.y+35);c.quadraticCurveTo(p.x-30+i*30,p.y+100,p.x-50+i*40,p.y+e.h);c.lineTo(p.x+e.w/2,p.y+e.h);c.fill();}c.fillStyle='#ffb85e';c.beginPath();c.arc(p.x+e.w/2,p.y+35,12,0,Math.PI*2);c.fill();c.fillStyle='#fff1bb';c.beginPath();c.arc(p.x+e.w/2,p.y+35,5,0,Math.PI*2);c.fill();}c.restore();}}
 private drawPlayer(c:CanvasRenderingContext2D){const p=this.player,s=this.worldToScreen(p.x,p.y);const run=Math.sin((p.runTime||0)*18)*2;const glow=c.createRadialGradient(s.x+17,s.y+32,4,s.x+17,s.y+32,60);glow.addColorStop(0,'rgba(255,190,80,.42)');glow.addColorStop(1,'rgba(255,190,80,0)');c.fillStyle=glow;c.fillRect(s.x-45,s.y-30,125,125);c.fillStyle='#0c1118';c.beginPath();c.moveTo(s.x+17,s.y);c.quadraticCurveTo(s.x+43,s.y+4,s.x+38,s.y+34);c.quadraticCurveTo(s.x+35,s.y+48,s.x+50,s.y+58);c.lineTo(s.x-2,s.y+58);c.quadraticCurveTo(s.x+8,s.y+42,s.x-1,s.y+31);c.quadraticCurveTo(s.x-7,s.y+5,s.x+17,s.y);c.fill();c.strokeStyle='#8fb6bf';c.lineWidth=2;c.stroke();c.fillStyle='#f8e8b1';c.beginPath();c.ellipse(s.x+11,s.y+27,5,8,0,0,Math.PI*2);c.ellipse(s.x+25,s.y+27,5,8,0,0,Math.PI*2);c.fill();c.fillStyle='#f3ad4e';c.beginPath();c.arc(s.x+18,s.y+43+run,10,0,Math.PI*2);c.fill();c.fillStyle='#f8d77a';c.beginPath();c.arc(s.x+18,s.y+43+run,5,0,Math.PI*2);c.fill();c.strokeStyle='#e4bf79';c.beginPath();c.moveTo(s.x+8,s.y+56);c.lineTo(s.x+3+(p.facing>0?7:-7),s.y+62);c.moveTo(s.x+28,s.y+56);c.lineTo(s.x+32+(p.facing>0?7:-7),s.y+62);c.stroke();if(p.dashTimer>0){c.globalAlpha=.35;c.fillStyle='#e9d27e';c.fillRect(s.x-p.facing*55,s.y+15,35,3);c.fillRect(s.x-p.facing*75,s.y+22,22,2);c.globalAlpha=1;}}
 private drawLantern(c:CanvasRenderingContext2D){const p=this.player,s=this.worldToScreen(p.x+31,p.y+24);const bob=Math.sin(this.time*3)*3;const r=14+this.pulse*14;const glow=c.createRadialGradient(s.x,s.y,2,s.x,s.y,70+r);glow.addColorStop(0,'rgba(255,201,94,.62)');glow.addColorStop(1,'rgba(255,201,94,0)');c.fillStyle=glow;c.fillRect(s.x-90,s.y-90,180,180);c.strokeStyle='#c58a3e';c.lineWidth=3;c.beginPath();c.arc(s.x,s.y+bob,10,0,Math.PI*2);c.stroke();c.fillStyle='#ffd37a';c.beginPath();c.arc(s.x,s.y+bob,6,0,Math.PI*2);c.fill();if(this.lanternThrown>0){const q=this.worldToScreen(this.lanternX,this.lanternY);c.strokeStyle='#f4c76d';c.beginPath();c.arc(q.x,q.y,10,0,Math.PI*2);c.stroke();}}
 private drawAtmosphere(c:CanvasRenderingContext2D){const darkness=clamp(.26+(.55-this.player.lantern/200)+(this.player.x>7600?.08:0),.2,.72);c.fillStyle=`rgba(2,5,10,${darkness})`;c.fillRect(0,0,VW,VH);const vign=c.createRadialGradient(VW/2,VH/2,170,VW/2,VH/2,700);vign.addColorStop(0,'rgba(0,0,0,0)');vign.addColorStop(1,'rgba(0,0,0,.58)');c.fillStyle=vign;c.fillRect(0,0,VW,VH);if(this.pulse>0){const q=this.worldToScreen(this.player.x+17,this.player.y+28);c.strokeStyle=`rgba(255,213,120,${this.pulse*.55})`;c.lineWidth=3;c.beginPath();c.arc(q.x,q.y,180+(1-this.pulse)*180,0,Math.PI*2);c.stroke();}if(this.memoryMode){c.strokeStyle='rgba(150,240,225,.55)';c.lineWidth=2;c.strokeRect(20,20,VW-40,VH-40);}if(this.horror>0){c.fillStyle=`rgba(80,0,70,${this.horror*.08})`;c.fillRect(0,0,VW,VH);}if(this.redFlash>0){c.fillStyle=`rgba(255,50,40,${this.redFlash*.16})`;c.fillRect(0,0,VW,VH);}}
}
function lateColor(x:number){return x>7600?'#26152f':'#141923';}
