import { areaAt, checkpoints, platforms, WORLD_HEIGHT, WORLD_WIDTH } from './level';
import { actAt, roomAt } from './campaign';
import type { AreaId, Enemy, GameSettings, GameSnapshot, InputState, Particle, Player, EndingChoice } from './types';

const VW=1280,VH=720;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
const hit=(a:{x:number;y:number;w:number;h:number},b:{x:number;y:number;w:number;h:number})=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
type Mode='title'|'playing'|'paused'|'ending';
type LanternMode='ILLUMINATE'|'REVEAL'|'PULSE'|'MEMORY'|'PURITY';
const beats:Array<[string,string,number]>=[
 ['THE FIRST WAKING','The lantern is warm. Someone was holding it before you.',0],
 ['THE HOLLOW','A bell rope sways without wind. The keeper left in a hurry.',720],
 ['THE DARK CAVE','Some things fear being remembered.',1580],
 ['THE MEMORY ROOM','For eight seconds, the dead city remembers how to breathe.',2740],
 ['THE BELL WARDEN','You should not have remembered that.',3920],
 ['THE THRESHOLD','What is real if memories can lie?',5300],
 ['THE MEMORY GARDEN','Every flower disappears when you stop remembering it.',6100],
 ['THE ARCHIVE','Every name here belongs to someone who thought they were the hero.',6840],
 ['THE MIRROR WARD','Your reflection is late. Do not wait for it to catch up.',8400],
 ['THE KEEPER','I was not protecting the Hollow from you. I was protecting you from the Hollow.',10160],
 ['THE EATER','I am not your enemy. I am everything you refused to remember.',10800]
];
const newPlayer=():Player=>({x:150,y:560,w:34,h:58,vx:0,vy:0,facing:1,grounded:false,coyote:0,jumpBuffer:0,dashTimer:0,dashCooldown:0,attackTimer:0,attackCooldown:0,burstTimer:0,burstCooldown:0,veilTimer:0,veilCooldown:0,health:4,maxHealth:4,lantern:100,maxLantern:100,invuln:0,hurtFlash:0,landTimer:0,runTime:0,hurtTimer:0});
function enemies():Enemy[]{return[
 {id:1,kind:'hollow',x:1020,y:540,w:38,h:60,vx:0,vy:0,hp:3,maxHp:3,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:0},
 {id:2,kind:'skitter',x:1390,y:640,w:52,h:34,vx:0,vy:0,hp:3,maxHp:3,grounded:false,hitFlash:0,alert:0,attackTimer:.8,attackWindup:0,dead:false,phase:.4},
 {id:3,kind:'hollow',x:1730,y:535,w:38,h:60,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:1},
 {id:4,kind:'watcher',x:2350,y:555,w:48,h:64,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:2},
 {id:5,kind:'hollow',x:3040,y:600,w:38,h:60,vx:0,vy:0,hp:6,maxHp:6,grounded:false,hitFlash:0,alert:0,attackTimer:1.2,attackWindup:0,dead:false,phase:3},
 {id:6,kind:'warden',x:4050,y:475,w:104,h:155,vx:0,vy:0,hp:16,maxHp:16,grounded:false,hitFlash:0,alert:0,attackTimer:1.6,attackWindup:0,dead:false,phase:0},
 {id:7,kind:'skitter',x:4880,y:605,w:52,h:34,vx:0,vy:0,hp:5,maxHp:5,grounded:false,hitFlash:0,alert:0,attackTimer:1,attackWindup:0,dead:false,phase:0},
 {id:8,kind:'watcher',x:6120,y:500,w:48,h:64,vx:0,vy:0,hp:6,maxHp:6,grounded:false,hitFlash:0,alert:0,attackTimer:1.5,attackWindup:0,dead:false,phase:0},
 {id:10,kind:'warden',x:7280,y:505,w:110,h:150,vx:0,vy:0,hp:18,maxHp:18,grounded:false,hitFlash:0,alert:0,attackTimer:1.4,attackWindup:0,dead:false,phase:0},
 {id:11,kind:'hollow',x:7900,y:570,w:38,h:60,vx:0,vy:0,hp:7,maxHp:7,grounded:false,hitFlash:0,alert:0,attackTimer:1.1,attackWindup:0,dead:false,phase:1.4},
 {id:12,kind:'watcher',x:8540,y:510,w:48,h:64,vx:0,vy:0,hp:8,maxHp:8,grounded:false,hitFlash:0,alert:0,attackTimer:1.3,attackWindup:0,dead:false,phase:2.1},
 {id:13,kind:'skitter',x:9280,y:575,w:52,h:34,vx:0,vy:0,hp:8,maxHp:8,grounded:false,hitFlash:0,alert:0,attackTimer:.9,attackWindup:0,dead:false,phase:2.8},
 {id:14,kind:'hollow',x:10020,y:615,w:38,h:60,vx:0,vy:0,hp:9,maxHp:9,grounded:false,hitFlash:0,alert:0,attackTimer:1.6,attackWindup:0,dead:false,phase:3.4},
 {id:15,kind:'warden',x:10360,y:410,w:110,h:155,vx:0,vy:0,hp:14,maxHp:14,grounded:false,hitFlash:0,alert:0,attackTimer:1.8,attackWindup:0,dead:false,phase:0},
 {id:9,kind:'eater',x:10920,y:490,w:150,h:165,vx:0,vy:0,hp:32,maxHp:32,grounded:false,hitFlash:0,alert:0,attackTimer:1.2,attackWindup:0,dead:false,phase:0}
];}
export class FlikkerEngine{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;player=newPlayer();enemies:Enemy[]=enemies();particles:Particle[]=[];input:InputState={left:false,right:false,jump:false,dash:false,attack:false,burst:false,pause:false,special:false};
 settings:GameSettings={reducedFlicker:false,screenShake:true,brightness:1,volume:.42,touchControls:true};mode:Mode='title';camera={x:0,shake:0};time=0;last=0;checkpoint=0;bossDefeated=false;endingChoice:EndingChoice=null;
 toast='THE LIGHT REMEMBERS';toastTimer=3;storyBeat=0;storyKicker=beats[0][0];storyLine=beats[0][1];storyTimer=0;lanternMode:LanternMode='ILLUMINATE';memoryMode=false;pulse=0;lanternThrown=0;lanternX=0;lanternY=0;lanternReturn=false;combo=0;comboWindow=0;hitStop=0;shake=0;horror=0;redFlash=0;endingTimer=0;lastArea:AreaId='THE THRESHOLD';onSnapshot:(s:GameSnapshot)=>void=()=>{};private raf=0;private audioCtx:AudioContext|null=null;private lastBossPhase=0;
 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable');this.ctx=c;this.resize();}
 start(){this.resize();window.addEventListener('resize',this.resize);window.addEventListener('keydown',this.key);this.raf=requestAnimationFrame(this.loop);}
 destroy(){window.removeEventListener('resize',this.resize);window.removeEventListener('keydown',this.key);cancelAnimationFrame(this.raf);}
 resize=()=>{const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(this.canvas.clientWidth*d));this.canvas.height=Math.max(1,Math.floor(this.canvas.clientHeight*d));};
 setSettings(s:GameSettings){this.settings=s;}setInput(i:Partial<InputState>){this.input={...this.input,...i};}touchAction(a:keyof InputState,p=true){if(a==='pause'){this.mode=this.mode==='paused'?'playing':'paused';return;}this.setInput({[a]:p});}setMode(m:Mode){this.mode=m;}
 begin(){this.ensureAudio();this.mode='playing';this.player=newPlayer();this.enemies=enemies();this.particles=[];this.checkpoint=0;checkpoints.forEach(c=>c.activated=false);this.bossDefeated=false;this.endingChoice=null;this.camera.x=0;this.time=0;this.lanternMode='ILLUMINATE';this.memoryMode=false;this.pulse=0;this.toast='THE LIGHT REMEMBERS';this.toastTimer=2.5;this.storyBeat=0;this.storyKicker=beats[0][0];this.storyLine=beats[0][1];this.storyTimer=4.8;this.lastArea='THE THRESHOLD';this.endingTimer=0;this.lastBossPhase=0;this.onSnapshot(this.getSnapshot());}
 private ensureAudio(){try{if(!this.audioCtx)this.audioCtx=new AudioContext();if(this.audioCtx.state==='suspended')void this.audioCtx.resume();}catch{}}
 private beep(freq:number,d=.08){try{if(!this.audioCtx)return;const o=this.audioCtx.createOscillator(),g=this.audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.0001,this.audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,this.audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,this.audioCtx.currentTime+d);o.connect(g);g.connect(this.audioCtx.destination);o.start();o.stop(this.audioCtx.currentTime+d+.02);}catch{}}
 private key=(e:KeyboardEvent)=>{if(this.mode!=='playing')return;if(e.code==='KeyQ'&&!e.repeat){this.cycleLantern();e.preventDefault();}if((e.code==='KeyL'||e.code==='KeyE')&&!e.repeat){this.useLanternAbility();e.preventDefault();}if(e.code==='KeyR'&&!e.repeat){this.recallLantern();e.preventDefault();}};
 private cycleLantern(){const m:LanternMode[]=['ILLUMINATE','REVEAL','PULSE','MEMORY','PURITY'];this.lanternMode=m[(m.indexOf(this.lanternMode)+1)%m.length];this.toast=this.lanternMode;this.toastTimer=.8;this.beep(420);}
 private useLanternAbility(){if(this.player.lantern<8)return;this.player.lantern-=8;switch(this.lanternMode){case'ILLUMINATE':this.pulse=.9;break;case'REVEAL':this.pulse=1.5;this.revealEnemies(460);break;case'PULSE':this.pulse=1.2;this.revealEnemies(520);break;case'MEMORY':this.memoryMode=!this.memoryMode;this.toast=this.memoryMode?'MEMORY / PAST':'PRESENT / RUIN';this.toastTimer=1.4;break;case'PURITY':this.pulse=1;this.revealEnemies(600);for(const e of this.enemies)if(!e.dead)e.vulnerable=true;break;}this.beep(620,.12);}
 private recallLantern(){if(this.lanternThrown<=0){this.lanternThrown=1;this.lanternX=this.player.x+this.player.facing*100;this.lanternY=this.player.y+25;this.toast='LANTERN THROW';this.toastTimer=.7;}else this.lanternReturn=true;}
 getSnapshot():GameSnapshot{const r=roomAt(this.player.x),boss=this.currentBoss(),g=this.ghost();return{mode:this.mode,area:areaAt(this.player.x),lantern:this.player.lantern,health:this.player.health,bossHealth:boss?.hp??0,bossMaxHealth:boss?.maxHp??0,checkpoint:this.checkpoint,toast:this.toastTimer>0?this.toast:'',storyKicker:this.storyKicker,storyLine:this.storyLine,storyTimer:this.storyTimer,storyBeat:this.storyBeat,ghostVisible:g.visible,ghostGesture:g.gesture,progress:clamp(this.player.x/(WORLD_WIDTH-500),0,1),act:r.act,actQuestion:r.act==='FEAR'?'Can you survive the dark?':r.act==='DOUBT'?'What is real if memories can lie?':'Who are you when memory cannot answer?',roomTitle:r.title,mechanic:r.mechanic,lanternMode:this.lanternMode,memoryMode:this.memoryMode,bossName:this.bossName(boss),bossPhase:boss?this.bossPhase(boss):0,endingChoice:this.endingChoice};}
 private bossName(e?:Enemy){if(!e)return '';if(e.kind==='eater')return 'THE EATER';if(e.x>10000)return 'THE KEEPER';if(e.x>6800)return 'THE CARTOGRAPHER';return 'THE BELL WARDEN';}
 private bossPhase(e:Enemy){if(e.kind==='eater')return Math.min(4,Math.max(1,Math.floor((1-e.hp/e.maxHp)*4)+1));return Math.min(3,Math.max(1,Math.floor((1-e.hp/e.maxHp)*3)+1));}
 private currentBoss(){return this.enemies.find(e=>(e.kind==='warden'||e.kind==='eater')&&!e.dead);}
 private ghost(){const late=this.player.x>8200,visible=late&&Math.sin(this.time*1.55)>0.73;return{visible,gesture:(visible?(this.player.x>9700?'watch':'point'):'wait') as 'wait'|'point'|'watch'|'vanish'};}
 private loop=(now:number)=>{const dt=Math.min((now-this.last)/1000||.016,.033);this.last=now;this.time+=dt;if(this.mode==='playing')this.update(dt);this.render();this.raf=requestAnimationFrame(this.loop);};
 private update(dt:number){if(this.hitStop>0){this.hitStop-=dt;this.updateParticles(dt);return;}const p=this.player,dir=(this.input.right?1:0)-(this.input.left?1:0);p.coyote=p.grounded?.12:Math.max(0,p.coyote-dt);p.jumpBuffer=this.input.jump?.12:Math.max(0,p.jumpBuffer-dt);p.dashCooldown=Math.max(0,p.dashCooldown-dt);p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.burstCooldown=Math.max(0,p.burstCooldown-dt);p.attackTimer=Math.max(0,p.attackTimer-dt);p.burstTimer=Math.max(0,p.burstTimer-dt);p.invuln=Math.max(0,p.invuln-dt);p.hurtFlash=Math.max(0,p.hurtFlash-dt);p.landTimer=Math.max(0,(p.landTimer||0)-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);this.toastTimer=Math.max(0,this.toastTimer-dt);this.storyTimer=Math.max(0,this.storyTimer-dt);this.pulse=Math.max(0,this.pulse-dt);this.horror=Math.max(0,this.horror-dt*.4);this.redFlash=Math.max(0,this.redFlash-dt*3);
  this.updateStory();if(this.input.jump&&p.jumpBuffer>0&&(p.grounded||p.coyote>0||p.veilTimer>0)){p.vy=-680;p.grounded=false;p.coyote=0;p.jumpBuffer=0;this.beep(280);this.spawnBurst(p.x+17,p.y+p.h,8,'#dbe6dd');}
  if(dir){p.facing=dir;p.vx=lerp(p.vx,dir*310,Math.min(1,dt*12));p.runTime=(p.runTime||0)+dt;}else{p.vx=lerp(p.vx,0,Math.min(1,dt*10));p.runTime=0;}if(this.input.dash&&p.dashCooldown<=0){p.dashTimer=.18;p.dashCooldown=.82;p.vx=p.facing*760;p.vy=0;p.invuln=.25;this.beep(180);this.spawnBurst(p.x,p.y+25,14,'#f2d38d');}if(p.dashTimer>0){p.dashTimer-=dt;p.vx=p.facing*760;p.vy=0;}else p.vy+=1700*dt;
  if(this.input.attack&&p.attackCooldown<=0)this.attack();if(this.input.burst&&p.burstCooldown<=0&&p.lantern>=15){p.burstCooldown=1.05;p.burstTimer=.5;p.lantern-=15;this.pulse=.8;this.revealEnemies(380);this.spawnBurst(p.x+17,p.y+28,30,'#ffd77b');this.beep(760,.15);}this.updateLantern(dt);this.updateLanternThrow(dt);const ox=p.x,oy=p.y;p.x=clamp(p.x+p.vx*dt,-30,WORLD_WIDTH-p.w-20);this.horizontal(p,ox);p.y+=p.vy*dt;p.grounded=false;this.vertical(p,oy);if(!p.grounded&&p.vy>80&&dir&&this.nearWall(p)){p.vy=Math.min(p.vy,140);p.veilTimer=.05;}if(p.y>WORLD_HEIGHT+100)this.respawn();
  this.updateEnemies(dt);this.updateParticles(dt);this.updateCheckpoints();const a=areaAt(p.x);if(a!==this.lastArea){this.lastArea=a;this.toast=a;this.toastTimer=2.2;this.spawnBurst(p.x,p.y,18,'#e8bd67');}const eater=this.enemies.find(e=>e.kind==='eater');if(eater?.dead&&!this.bossDefeated){this.bossDefeated=true;this.storyKicker='THE LIGHT REMEMBERS';this.storyLine='Inside the Eater: a name, still warm. Mara. Last bearer.';this.storyTimer=7;this.toast='THE CHOICE IS YOURS';this.toastTimer=4;this.endingTimer=8;this.endingChoice='FREEDOM';}if(this.bossDefeated){this.endingTimer-=dt;if(this.endingTimer<=0)this.mode='ending';}
  this.camera.x=lerp(this.camera.x,clamp(p.x-VW*.42,0,WORLD_WIDTH-VW),Math.min(1,dt*4.5));this.camera.shake=this.settings.screenShake?this.shake:0;this.shake=Math.max(0,this.shake-dt*4);this.input.jump=false;this.input.dash=false;this.input.attack=false;this.input.burst=false;this.input.special=false;}
 chooseEnding(choice:EndingChoice){if(!this.bossDefeated||!choice)return;this.endingChoice=choice;this.endingTimer=.8;this.toast=choice==='LIGHT'?'THE LIGHT':choice==='EATER'?'THE EATER':'THE FLIKKER';this.toastTimer=2;this.onSnapshot(this.getSnapshot());}
 private updateStory(){for(let i=beats.length-1;i>=0;i--)if(this.player.x>=beats[i][2]&&i>=this.storyBeat){this.storyBeat=i;this.storyKicker=beats[i][0];this.storyLine=beats[i][1];this.storyTimer=4.2;this.toast=beats[i][0];this.toastTimer=2.2;break;}}
 private updateLantern(dt:number){const a=areaAt(this.player.x),safe=a==='THE THRESHOLD'||a==='THE HOLLOW'||a==='THE SUNKEN GARDEN';const drain=(safe?.22:.34)+(this.player.x>7600?.16:0);this.player.lantern=clamp(this.player.lantern+(safe?.7:0)-drain*dt,0,100);if(this.player.lantern<18){this.horror=.7;if(this.toastTimer<=0){this.toast='THE DARK HAS FOUND YOU';this.toastTimer=1.2;}}if(this.player.x>5300&&this.player.x<6680&&this.memoryMode)this.player.lantern=clamp(this.player.lantern+.35,0,100);}
 private updateLanternThrow(dt:number){if(this.lanternThrown<=0)return;const target=this.lanternReturn?this.player.x+17:this.lanternX+this.player.facing*420*dt;this.lanternX=this.lanternReturn?lerp(this.lanternX,target,Math.min(1,dt*8)):target;this.lanternY=lerp(this.lanternY,this.player.y+24,.08);if(this.lanternReturn&&Math.abs(this.lanternX-(this.player.x+17))<24){this.lanternThrown=0;this.lanternReturn=false;this.toast='LANTERN RETURN';this.toastTimer=.7;}}
 private revealEnemies(r:number){for(const e of this.enemies)if(!e.dead&&Math.hypot(this.player.x-e.x,this.player.y-e.y)<r){e.alert=1;e.vulnerable=true;}}
 private attack(){const p=this.player;if(this.comboWindow<=0)this.combo=0;this.combo=this.combo%3+1;this.comboWindow=.48;p.attackTimer=.24;p.attackCooldown=.19;const range=this.combo===3?112:82;const hb={x:p.facing>0?p.x+8:p.x-range+28,y:p.y+(this.combo===3?-12:8),w:range,h:this.combo===3?78:54};for(const e of this.enemies){if(e.dead||!hit(hb,e)||((e.kind==='warden'||e.kind==='eater')&&!e.vulnerable))continue;let dmg=this.combo===3?3:1;if(this.lanternMode==='PURITY')dmg++;e.hp-=dmg;e.hitFlash=.18;e.vx=p.facing*(280+this.combo*60);e.vy=this.combo===3?-430:-210;this.hitStop=.06;this.shake=.2;this.spawnBurst(e.x+e.w/2,e.y+e.h/2,11,'#ffe2a0');if(e.hp<=0)e.dead=true;}this.toast=this.combo===3?'FALLING STAR':this.combo===2?'RISING LIGHT':'SPARK';this.toastTimer=.35;this.beep(360+this.combo*90);}
 private updateEnemies(dt:number){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer-=dt;const dist=Math.abs(p.x-e.x),d=p.x-e.x;if(e.kind==='warden'||e.kind==='eater'){this.updateBoss(e,dt);continue;}if(e.x>5800&&e.x<6600&&dist<120&&e.id===8){p.lantern=clamp(p.lantern-dt*7,0,100);this.horror=.45;}if(e.kind==='watcher'&&e.x>8200){e.vx=dist<440?Math.sign(d)*45:0;e.y+=Math.sin(this.time*2+e.id)*.18;}else if(dist<430||e.alert>0)e.vx=Math.sign(d)*((e.kind==='skitter'?120:70)+(e.x>7600?30:0));else e.vx=Math.sin(this.time+e.id)*12;e.x+=e.vx*dt;this.enemyGround(e);if(dist<82&&e.attackTimer<=0){e.attackTimer=e.kind==='skitter'?.9:1.35;this.damagePlayer(1);}}}
 private updateBoss(e:Enemy,dt:number){const p=this.player;const phase=this.bossPhase(e);e.phase=phase;if(phase!==this.lastBossPhase&&e.kind==='eater'){this.lastBossPhase=phase;this.toast=['','HUNGER','MEMORY','DOUBT','FLIK'][phase]||'THE EATER';this.toastTimer=1.4;this.horror=.8;this.shake=.5;this.spawnBurst(e.x+e.w/2,e.y+e.h/2,35,phase>=3?'#bd77d4':'#e6b25f');}if(e.attackTimer>0){e.attackTimer-=dt;return;}e.attackTimer=e.kind==='eater'?1.05:.95;if(e.kind==='eater'){if(phase===1)this.damagePlayer(1);else if(phase===2){this.revealEnemies(520);this.damagePlayer(1);}else if(phase===3){this.memoryMode=!this.memoryMode;this.horror=1;this.shake=.65;}else{this.damagePlayer(1);this.pulse=1;}}else if(e.x>10000){this.toast='THE KEEPER WATCHES';this.toastTimer=.7;this.horror=.55;this.pulse=.6;}else{this.toast='THE MAP MOVES';this.toastTimer=.6;this.pulse=.45;this.shake=.3;}if(e.x>6800&&e.x<8000&&Math.sin(this.time*2.3)>.93){e.x=7280+Math.sin(this.time)*110;e.vulnerable=false;this.spawnBurst(e.x,e.y+60,14,'#8fd7d1');}if(e.x>10000&&e.kind==='warden'&&Math.sin(this.time*1.7)>.96){e.x=10320+Math.sin(this.time*1.1)*120;e.y=390;this.spawnBurst(e.x,e.y+70,18,'#9f78bf');}}
 private enemyGround(e:Enemy){const s=platforms.find(q=>e.x+e.w>q.x&&e.x<q.x+q.w&&Math.abs(e.y+e.h-q.y)<14);if(s)e.y=s.y-e.h;}
 private damagePlayer(n:number){const p=this.player;if(p.invuln>0)return;p.health=clamp(p.health-n,0,p.maxHealth);p.hurtFlash=.25;p.invuln=.55;this.redFlash=.5;this.shake=.45;this.beep(110);if(p.health<=0)this.respawn();}
 private updateCheckpoints(){for(let i=0;i<checkpoints.length;i++){const c=checkpoints[i];if(!c.activated&&this.player.x>=c.x){c.activated=true;this.checkpoint=i;this.player.health=this.player.maxHealth;this.player.lantern=this.player.maxLantern;this.toast='LUMEN SHRINE';this.toastTimer=1.2;this.spawnBurst(c.x,c.y-20,24,'#f4cf76');}}}
 private respawn(){const c=checkpoints[this.checkpoint]||checkpoints[0];this.player.x=c.x;this.player.y=c.y-this.player.h-5;this.player.vx=0;this.player.vy=0;this.player.health=this.player.maxHealth;this.player.lantern=Math.max(60,this.player.maxLantern);this.redFlash=0;this.horror=0;this.toast='THE LANTERN BRINGS YOU BACK';this.toastTimer=1.8;}
 private horizontal(b:Player,oldX:number){if(!b.vx)return;for(const s of platforms){if(s.oneWay)continue;if(b.y+b.h<=s.y+5||b.y>=s.y+s.h)continue;if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX+b.w<=s.x&&b.vx>0){b.x=s.x-b.w-.01;b.vx=0;}else if(b.x<s.x+s.w&&b.x+b.w>s.x&&oldX>=s.x+s.w&&b.vx<0){b.x=s.x+s.w+.01;b.vx=0;}}}
 private vertical(b:Player,oldY:number){if(b.vy<0)return;let land:any;for(const s of platforms){const crossed=oldY+b.h<=s.y+4&&b.y+b.h>=s.y;if(crossed&&b.x+b.w>s.x+3&&b.x<s.x+s.w-3&&(!s.oneWay||oldY+b.h<=s.y+2)&&(!land||s.y<land.y))land=s;}if(land){b.y=land.y-b.h;b.vy=0;b.grounded=true;}}
 private nearWall(p:Player){return platforms.some(s=>p.y+p.h>s.y+5&&p.y<s.y+s.h&&(Math.abs(p.x+p.w-s.x)<10||Math.abs(p.x-(s.x+s.w))<10));}
 private spawnBurst(x:number,y:number,n:number,color:string){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*170;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.55,maxLife:.9,size:1+Math.random()*3,color,gravity:40});}}
 private updateParticles(dt:number){for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=(q.gravity||0)*dt;}this.particles=this.particles.filter(q=>q.life>0);}
 private world(x:number,y:number){return{x:x-this.camera.x,y};}
 private render(){const c=this.ctx;c.save();const sx=this.shake*(Math.random()-.5)*8,sy=this.shake*(Math.random()-.5)*8;c.clearRect(0,0,this.canvas.width,this.canvas.height);c.scale(this.canvas.width/VW,this.canvas.height/VH);c.translate(sx,sy);this.drawSky(c);this.drawWorld(c);this.drawMemory(c);this.drawEntities(c);this.drawPlayer(c);this.drawLantern(c);this.drawParticles(c);this.drawAtmosphere(c);c.restore();}
 private drawSky(c:CanvasRenderingContext2D){const act=actAt(this.player.x);const top=act==='FEAR'?'#07131d':act==='DOUBT'?'#120d20':'#0b0716',bot=act==='FEAR'?'#10232d':act==='DOUBT'?'#32173b':'#35123d';const g=c.createLinearGradient(0,0,0,VH);g.addColorStop(0,top);g.addColorStop(1,bot);c.fillStyle=g;c.fillRect(0,0,VW,VH);for(let i=0;i<34;i++){const px=(i*157-this.camera.x*.12)%1450,py=40+(i*71)%400;c.fillStyle=i%4?'#243744':'#746b59';c.fillRect(px,py,2+(i%3),90+(i%5)*25);}const moon=act==='IDENTITY'?'#d8a6e5':'#c7e8e6';c.fillStyle=moon;c.beginPath();c.arc(1010-this.camera.x*.035,88,38,0,Math.PI*2);c.fill();c.fillStyle=top;c.beginPath();c.arc(1026-this.camera.x*.035,78,35,0,Math.PI*2);c.fill();for(let i=0;i<15;i++){const bx=(i*170-this.camera.x*.08)%1500;c.fillStyle=act==='IDENTITY'?'#25112e':'#142832';c.fillRect(bx,390-(i%3)*40,70+(i%4)*30,180);}}
 private drawWorld(c:CanvasRenderingContext2D){const start=this.camera.x-120,end=this.camera.x+VW+120;for(const s of platforms){if(s.x+s.w<start||s.x>end)continue;const p=this.world(s.x,s.y);c.fillStyle=s.material==='water'?'#173b40':s.material==='wood'?'#3a2e2b':'#202b32';c.fillRect(p.x,p.y,s.w,s.h);c.fillStyle=s.moss?'#59634e':'#34414a';c.fillRect(p.x,p.y,s.w,7);if(s.moss){for(let i=0;i<s.w/40;i++){c.fillStyle='#9da976';c.fillRect(p.x+i*40+8,p.y-4-(i%2)*3,2,7);}}}for(let i=0;i<20;i++){const wx=380+i*610,x=wx-this.camera.x;if(x<-160||x>VW+160)continue;c.strokeStyle=actAt(this.player.x)==='IDENTITY'?'#2b1a35':'#213943';c.lineWidth=18;c.beginPath();c.moveTo(x,565);c.lineTo(x,250+(i%3)*35);c.quadraticCurveTo(x+80,175+(i%3)*25,x+160,250+(i%3)*35);c.lineTo(x+160,565);c.stroke();c.fillStyle='#d99b45';c.beginPath();c.arc(x+80,275+(i%3)*35,4,0,Math.PI*2);c.fill();}}
 private drawMemory(c:CanvasRenderingContext2D){const x=this.player.x;if(x>5300&&x<6680){for(let i=0;i<22;i++){const q=this.world(5360+i*62,600-(i%4)*48);c.globalAlpha=this.memoryMode?.7:.18;c.strokeStyle=this.memoryMode?'#8ee1d2':'#58706c';c.lineWidth=2;c.beginPath();c.arc(q.x,q.y,8+(i%3)*3,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(q.x,q.y);c.lineTo(q.x,q.y-35-(i%3)*10);c.stroke();}c.globalAlpha=1;}if(x>6680&&x<8400){for(let i=0;i<18;i++){const q=this.world(6720+i*105,300+(i%4)*70);c.fillStyle=this.memoryMode?'#bfece0':'#7f6e85';c.globalAlpha=this.memoryMode?.8:.3;c.fillRect(q.x,q.y,48,70);c.fillStyle='#e7d4b2';c.fillRect(q.x+8,q.y+12,30,2);c.fillRect(q.x+8,q.y+25,24,2);}c.globalAlpha=1;}if(x>8400&&x<9740){const q=this.world(this.player.x+180,170);c.globalAlpha=.22;c.strokeStyle='#b88ed0';c.lineWidth=4;c.strokeRect(q.x,q.y,260,430);c.globalAlpha=1;}}
 private drawEntities(c:CanvasRenderingContext2D){for(const e of this.enemies){if(e.dead)continue;const p=this.world(e.x,e.y);c.save();if(e.hitFlash>0)c.globalAlpha=.45;const late=e.x>7600;if(e.kind==='hollow'){c.fillStyle='#111722';c.beginPath();c.ellipse(p.x+19,p.y+34,20,29,0,0,Math.PI*2);c.fill();c.fillStyle='#d56b46';c.beginPath();c.arc(p.x+27,p.y+25,4,0,Math.PI*2);c.fill();}else if(e.kind==='skitter'){c.fillStyle='#14131d';c.beginPath();c.ellipse(p.x+26,p.y+17,27,16,0,0,Math.PI*2);c.fill();for(let i=0;i<4;i++){c.strokeStyle='#363047';c.beginPath();c.moveTo(p.x+8+i*12,p.y+20);c.lineTo(p.x-5+i*8,p.y+34);c.stroke();}c.fillStyle='#e08a4e';c.beginPath();c.arc(p.x+31,p.y+13,3,0,Math.PI*2);c.fill();}else if(e.kind==='watcher'){c.fillStyle=late?'#26152f':'#141923';c.beginPath();c.moveTo(p.x+24,p.y);c.lineTo(p.x+48,p.y+54);c.lineTo(p.x+30,p.y+64);c.lineTo(p.x+6,p.y+54);c.closePath();c.fill();c.fillStyle='#e6a06d';c.beginPath();c.arc(p.x+25,p.y+26,5,0,Math.PI*2);c.fill();}else if(e.kind==='warden'&&e.x>10000){c.fillStyle='#100b17';for(let i=0;i<7;i++){c.beginPath();c.moveTo(p.x+55,p.y+20);c.quadraticCurveTo(p.x-20+i*25,p.y+95,p.x-30+i*28,p.y+155);c.lineTo(p.x+55,p.y+155);c.fill();}c.strokeStyle='#a27bb7';c.lineWidth=3;c.beginPath();c.arc(p.x+55,p.y+48,24,0,Math.PI*2);c.stroke();c.fillStyle='#f0b65c';c.beginPath();c.arc(p.x+55,p.y+48,8,0,Math.PI*2);c.fill();}else if(e.kind==='warden'&&e.x>6800){c.fillStyle='#15171d';c.beginPath();c.moveTo(p.x+55,p.y+5);c.lineTo(p.x+105,p.y+40);c.lineTo(p.x+96,p.y+145);c.lineTo(p.x+12,p.y+145);c.lineTo(p.x+5,p.y+40);c.closePath();c.fill();c.strokeStyle='#79b7b3';c.lineWidth=3;c.stroke();for(let i=0;i<4;i++){c.strokeStyle='#719b9b';c.beginPath();c.moveTo(p.x+15+i*24,p.y+20);c.lineTo(p.x+90-i*18,p.y+120);c.stroke();}c.fillStyle='#bce8df';c.fillRect(p.x+45,p.y+55,20,8);}else if(e.kind==='warden'){c.fillStyle='#171520';c.fillRect(p.x+20,p.y+20,e.w-40,e.h-20);c.strokeStyle='#8b6b57';c.lineWidth=5;c.strokeRect(p.x+18,p.y+18,e.w-36,e.h-28);c.fillStyle='#f0b65c';c.beginPath();c.arc(p.x+e.w/2,p.y+52,12,0,Math.PI*2);c.fill();c.strokeStyle='#d7b06b';c.beginPath();c.arc(p.x+e.w/2,p.y+40,28,Math.PI,Math.PI*2);c.stroke();}else{c.fillStyle='#100817';for(let i=0;i<7;i++){c.beginPath();c.moveTo(p.x+e.w/2,p.y+35);c.quadraticCurveTo(p.x-30+i*30,p.y+100,p.x-50+i*40,p.y+e.h);c.lineTo(p.x+e.w/2,p.y+e.h);c.fill();}c.fillStyle='#ffb85e';c.beginPath();c.arc(p.x+e.w/2,p.y+35,13,0,Math.PI*2);c.fill();c.fillStyle='#fff1bb';c.beginPath();c.arc(p.x+e.w/2,p.y+35,5,0,Math.PI*2);c.fill();if(this.bossPhase(e)>=3){c.strokeStyle='#c48bd4';c.globalAlpha=.55;c.lineWidth=3;c.beginPath();c.arc(p.x+e.w/2,p.y+35,55+Math.sin(this.time*3)*8,0,Math.PI*2);c.stroke();}}if(e.kind==='warden'||e.kind==='eater'){c.globalAlpha=.12+.08*Math.sin(this.time*4);c.fillStyle=e.x>10000?'#9c63c6':e.x>6800?'#64c4bb':'#c27a6a';c.beginPath();c.arc(p.x+e.w/2,p.y+e.h/2,90,0,Math.PI*2);c.fill();}c.restore();}}
 private drawPlayer(c:CanvasRenderingContext2D){const p=this.player,s=this.world(p.x,p.y),run=Math.sin((p.runTime||0)*18)*2;const glow=c.createRadialGradient(s.x+17,s.y+32,4,s.x+17,s.y+32,62);glow.addColorStop(0,'rgba(255,190,80,.48)');glow.addColorStop(1,'rgba(255,190,80,0)');c.fillStyle=glow;c.fillRect(s.x-45,s.y-30,125,125);c.fillStyle='#0c1118';c.beginPath();c.moveTo(s.x+17,s.y);c.quadraticCurveTo(s.x+43,s.y+4,s.x+38,s.y+34);c.quadraticCurveTo(s.x+35,s.y+48,s.x+50,s.y+58);c.lineTo(s.x-2,s.y+58);c.quadraticCurveTo(s.x+8,s.y+42,s.x-1,s.y+31);c.quadraticCurveTo(s.x-7,s.y+5,s.x+17,s.y);c.fill();c.strokeStyle='#8fb6bf';c.lineWidth=2;c.stroke();c.fillStyle='#f8e8b1';c.beginPath();c.ellipse(s.x+11,s.y+27,5,8,0,0,Math.PI*2);c.ellipse(s.x+25,s.y+27,5,8,0,0,Math.PI*2);c.fill();c.fillStyle='#f3ad4e';c.beginPath();c.arc(s.x+18,s.y+43+run,10,0,Math.PI*2);c.fill();c.fillStyle='#f8d77a';c.beginPath();c.arc(s.x+18,s.y+43+run,5,0,Math.PI*2);c.fill();if(this.memoryMode){c.globalAlpha=.25;c.fillStyle='#8de4d7';c.beginPath();c.arc(s.x+18,s.y+30,45,0,Math.PI*2);c.fill();c.globalAlpha=1;}if(p.dashTimer>0){c.globalAlpha=.35;c.fillStyle='#e9d27e';c.fillRect(s.x-p.facing*55,s.y+15,35,3);c.fillRect(s.x-p.facing*75,s.y+22,22,2);c.globalAlpha=1;}}
 private drawLantern(c:CanvasRenderingContext2D){const p=this.player,s=this.world(p.x+31,p.y+24),bob=Math.sin(this.time*3)*3,r=14+this.pulse*14;const glow=c.createRadialGradient(s.x,s.y,2,s.x,s.y,70+r);glow.addColorStop(0,'rgba(255,201,94,.68)');glow.addColorStop(1,'rgba(255,201,94,0)');c.fillStyle=glow;c.fillRect(s.x-95,s.y-95,190,190);c.strokeStyle='#c58a3e';c.lineWidth=3;c.beginPath();c.arc(s.x,s.y+bob,10,0,Math.PI*2);c.stroke();c.fillStyle='#ffd37a';c.beginPath();c.arc(s.x,s.y+bob,6,0,Math.PI*2);c.fill();if(this.lanternThrown>0){const q=this.world(this.lanternX,this.lanternY);c.strokeStyle='#f4c76d';c.beginPath();c.arc(q.x,q.y,11,0,Math.PI*2);c.stroke();}}
 private drawParticles(c:CanvasRenderingContext2D){for(const q of this.particles){const p=this.world(q.x,q.y);c.globalAlpha=clamp(q.life/q.maxLife,0,1);c.fillStyle=q.color;c.beginPath();c.arc(p.x,p.y,q.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 private drawAtmosphere(c:CanvasRenderingContext2D){const darkness=clamp(.24+(.55-this.player.lantern/200)+(actAt(this.player.x)==='IDENTITY'?.1:0),.2,.76);c.fillStyle=`rgba(2,5,10,${darkness})`;c.fillRect(0,0,VW,VH);const vign=c.createRadialGradient(VW/2,VH/2,170,VW/2,VH/2,700);vign.addColorStop(0,'rgba(0,0,0,0)');vign.addColorStop(1,'rgba(0,0,0,.62)');c.fillStyle=vign;c.fillRect(0,0,VW,VH);if(this.pulse>0){const q=this.world(this.player.x+17,this.player.y+28);c.strokeStyle=`rgba(255,213,120,${this.pulse*.55})`;c.lineWidth=3;c.beginPath();c.arc(q.x,q.y,180+(1-this.pulse)*180,0,Math.PI*2);c.stroke();}if(this.memoryMode){c.fillStyle='rgba(120,230,215,.07)';c.fillRect(0,0,VW,VH);c.strokeStyle='rgba(150,240,225,.5)';c.lineWidth=2;c.strokeRect(20,20,VW-40,VH-40);}if(this.horror>0){c.fillStyle=`rgba(80,0,70,${this.horror*.08})`;c.fillRect(0,0,VW,VH);}if(this.redFlash>0){c.fillStyle=`rgba(255,50,40,${this.redFlash*.16})`;c.fillRect(0,0,VW,VH);}}
}
