import { GameAudio } from './audio';
import { areaAt, checkpoints, makeEnemies, platforms, WORLD_HEIGHT, WORLD_WIDTH } from './level';
import type { AreaId, Enemy, GameSettings, GameSnapshot, InputState, Particle, Player, Platform } from './types';

const VW=1280, VH=720;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
const overlap=(a:{x:number;y:number;w:number;h:number},b:{x:number;y:number;w:number;h:number})=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;

type ExtendedInput=InputState&{special?:boolean};
const newPlayer=():Player=>({x:150,y:570,w:30,h:54,vx:0,vy:0,facing:1,grounded:false,coyote:0,jumpBuffer:0,dashTimer:0,dashCooldown:0,attackTimer:0,attackCooldown:0,burstTimer:0,burstCooldown:0,veilTimer:0,veilCooldown:0,health:4,maxHealth:4,lantern:100,maxLantern:100,invuln:0,hurtFlash:0,landTimer:0,runTime:0,hurtTimer:0});
const beats:Array<[string,string,number,number]>=[
 ['THE FIRST WAKING','The lantern is warm. Someone was holding it before you.',0,4.8],
 ['THE HOLLOW','A bell rope sways without wind. The keeper left in a hurry.',720,3.8],
 ['THE SHIFTING HALL','Another bearer marked the stones: not a map. A warning.',1560,4.4],
 ['THE SUNKEN GARDEN','Roots drink from the old road. Something underneath remembers.',2740,4.2],
 ['THE CHAPEL','Three lanterns. Three names scratched away.',3420,4.2],
 ['THE BELL WARDEN','The armor is still ringing. Something inside it has learned your footsteps.',3920,4.4],
 ['THE DESCENT','The ghosts point down. They do not follow.',4300,3.8],
 ['THE ARCHIVE','Every name here belongs to someone who thought they were the hero.',6840,4.2],
 ['THE MIRROR WARD','Your reflection is late. Do not wait for it to catch up.',8400,4.2],
 ['THE LAST VESTIBULE','Mara did not choose you. She chose what would be left of you.',9740,4.4],
 ['THE BELL CHAMBER','The bell does not call the dead. It keeps them here.',5700,4.2],
 ['THE DEEP','Do not let the lantern see you. It will show you what you owe.',10800,4.4],
] as const;

export class FlikkerEngine {
 canvas:HTMLCanvasElement; ctx:CanvasRenderingContext2D; player=newPlayer(); enemies:Enemy[]=makeEnemies(); particles:Particle[]=[];
 input:ExtendedInput={left:false,right:false,jump:false,dash:false,attack:false,burst:false,pause:false,special:false};
 settings:GameSettings={reducedFlicker:false,screenShake:true,brightness:1,volume:.42,touchControls:true};
 camera={x:0,shake:0}; time=0; last=0; mode:'title'|'playing'|'paused'|'ending'='title';
 toast='The light remembers the way'; toastTimer=4; checkpoint=0; bossDefeated=false;
 storyBeat=0; storyKicker=beats[0][0]; storyLine=beats[0][1]; storyTimer=0; ghostGesture:'wait'|'point'|'watch'|'vanish'='wait'; endingTimer=0;
 onSnapshot:(s:GameSnapshot)=>void=()=>{};
 private audio=new GameAudio(); private raf=0; private lastArea:AreaId='THE THRESHOLD'; private hitStop=0; private shake=0; private ring=0; private specialRing=0; private horror=0; private redFlash=0; private lowLanternWarning=false;
 private combo=0; private comboWindow=0; private specialCooldown=0; private specialTimer=0; private dashTrail:{x:number;y:number;a:number}[]=[];
 private stars=Array.from({length:90},(_,i)=>({x:(i*83)%VW,y:30+(i*47)%470,s:.2+(i%6)*.1}));
 constructor(canvas:HTMLCanvasElement){this.canvas=canvas;const c=canvas.getContext('2d');if(!c)throw new Error('Canvas unavailable');this.ctx=c;this.resize();}
 start(){this.resize();window.addEventListener('resize',this.resize);window.addEventListener('keydown',this.key);this.raf=requestAnimationFrame(this.loop);}
 destroy(){window.removeEventListener('resize',this.resize);window.removeEventListener('keydown',this.key);cancelAnimationFrame(this.raf);}
 private key=(e:KeyboardEvent)=>{if(e.code==='KeyE'&&!e.repeat&&this.mode==='playing')this.input.special=true;};
 resize=()=>{const d=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.floor(this.canvas.clientWidth*d));this.canvas.height=Math.max(1,Math.floor(this.canvas.clientHeight*d));};
  begin(){this.audio.init();this.mode='playing';this.player=newPlayer();this.enemies=makeEnemies();this.particles=[];this.checkpoint=0;this.bossDefeated=false;this.storyBeat=0;this.storyKicker=beats[0][0];this.storyLine=beats[0][1];this.storyTimer=beats[0][3];this.lastArea='THE THRESHOLD';this.camera.x=0;this.horror=0;this.redFlash=0;this.lowLanternWarning=false;this.toast='The light remembers the way';this.toastTimer=3;this.addBurst(180,610,'gold',25);this.onSnapshot(this.getSnapshot());}
 setMode(m:'title'|'playing'|'paused'|'ending'){this.mode=m;}
 setSettings(s:GameSettings){this.settings=s;this.audio.setVolume(s.volume);}
 setInput(i:Partial<ExtendedInput>){this.input={...this.input,...i};}
 touchAction(a:keyof ExtendedInput,p=true){if(a==='pause'){this.mode=this.mode==='paused'?'playing':'paused';return;}this.setInput({[a]:p});}
 getSnapshot():GameSnapshot{const b=this.enemies.find(e=>(e.kind==='warden'||e.kind==='eater')&&!e.dead)||this.enemies.find(e=>e.kind==='eater');const g=this.ghost();return{mode:this.mode,area:areaAt(this.player.x),lantern:this.player.lantern,health:this.player.health,bossHealth:b?b.hp:0,bossMaxHealth:b?b.maxHp:9,checkpoint:this.checkpoint,toast:this.toastTimer>0?this.toast:'',storyKicker:this.storyKicker,storyLine:this.storyLine,storyTimer:this.storyTimer,storyBeat:this.storyBeat,ghostVisible:g.visible,ghostGesture:this.ghostGesture,progress:clamp(this.player.x/(WORLD_WIDTH-500),0,1)};}
 private loop=(now:number)=>{const dt=Math.min((now-this.last)/1000||.016,.034);this.last=now;this.time+=dt;if(this.mode==='playing')this.update(dt);this.render();this.raf=requestAnimationFrame(this.loop);};
 private update(dt:number){if(this.hitStop>0){this.hitStop-=dt;this.updateParticles(dt);return;}const p=this.player;const was=p.grounded;
   p.coyote=p.grounded ? .12 : Math.max(0,p.coyote-dt);p.jumpBuffer=this.input.jump ? .12 : Math.max(0,p.jumpBuffer-dt);p.dashCooldown=Math.max(0,p.dashCooldown-dt);p.attackCooldown=Math.max(0,p.attackCooldown-dt);p.burstCooldown=Math.max(0,p.burstCooldown-dt);this.specialCooldown=Math.max(0,this.specialCooldown-dt);this.comboWindow=Math.max(0,this.comboWindow-dt);p.attackTimer=Math.max(0,p.attackTimer-dt);p.burstTimer=Math.max(0,p.burstTimer-dt);p.invuln=Math.max(0,p.invuln-dt);p.hurtFlash=Math.max(0,p.hurtFlash-dt);p.landTimer=Math.max(0,(p.landTimer||0)-dt);p.hurtTimer=Math.max(0,(p.hurtTimer||0)-dt);this.specialTimer=Math.max(0,this.specialTimer-dt);this.horror=Math.max(0,this.horror-dt*.32);this.redFlash=Math.max(0,this.redFlash-dt*2.8);if(this.toastTimer>0)this.toastTimer-=dt;if(this.storyTimer>0)this.storyTimer-=dt;if(p.lantern<22&&!this.lowLanternWarning){this.lowLanternWarning=true;this.horror=.9;this.toast='THE DARK HAS FOUND YOU';this.toastTimer=1.8;this.addBurst(p.x+15,p.y+26,'flare',18);}if(p.lantern>30)this.lowLanternWarning=false;
  this.story();
  if(this.input.jump&&p.jumpBuffer>0&&p.coyote>0){p.vy=-635;p.grounded=false;p.coyote=0;p.jumpBuffer=0;this.audio.tone(270,.1,'triangle',.05,80);this.dust(p.x+15,p.y+p.h,7,'#d8d5bd');}
  if(!this.input.jump&&p.vy<-280)p.vy+=990*dt;
  const dir=(this.input.right?1:0)-(this.input.left?1:0);if(dir){p.facing=dir;p.vx=lerp(p.vx,dir*275,Math.min(1,dt*13));p.runTime=(p.runTime||0)+dt*10;}else{p.vx=lerp(p.vx,0,Math.min(1,dt*11));p.runTime=0;}
  if(this.input.dash&&p.dashCooldown<=0&&!this.specialTimer){p.dashTimer=.18;p.dashCooldown=.68;p.vx=p.facing*650;p.vy=0;p.invuln=Math.max(p.invuln,.22);this.audio.dash();this.addDashTrail();this.dust(p.x,p.y+p.h,14,'#e6d38d');}
  if(p.dashTimer>0){p.dashTimer-=dt;p.vx=p.facing*650;p.vy=0;this.addDashTrail();}else if(this.specialTimer<=0)p.vy+=1650*dt;
  if(this.input.attack&&p.attackCooldown<=0&&this.specialTimer<=0)this.attack();
  if(this.input.burst&&p.burstCooldown<=0&&p.lantern>=18){p.burstTimer=.5;p.burstCooldown=1.05;p.lantern-=18;this.ring=1;this.audio.burst();this.addBurst(p.x+15,p.y+26,'flare',40);this.reveal();}
  if(this.input.special&&this.specialCooldown<=0&&p.lantern>=28)this.lumenStep();
  p.lantern=clamp(p.lantern-dt*(.46+(this.lastArea==='SHIFTING HALL' ? .14 : 0)),0,p.maxLantern);
   const px=p.x,py=p.y;p.x+=p.vx*dt;p.x=clamp(p.x,-48,WORLD_WIDTH-p.w-20);this.horizontal(p,px,platforms);p.y+=p.vy*dt;p.grounded=false;this.vertical(p,py,platforms);if(p.y>WORLD_HEIGHT)this.respawn();if(!was&&p.grounded){p.landTimer=.18;this.dust(p.x+15,p.y+p.h,12,'#a7aea0');}
  this.enemiesUpdate(dt);this.updateParticles(dt);this.checkpoints();this.ring=Math.max(0,this.ring-dt*2.5);this.specialRing=Math.max(0,this.specialRing-dt*3);this.shake=Math.max(0,this.shake-dt*3);
  const a=areaAt(p.x);if(a!==this.lastArea){this.lastArea=a;this.toast=a;this.toastTimer=2.6;this.addBurst(p.x,p.y,'gold',20);}const eater=this.enemies.find(e=>e.kind==='eater');if(eater&&eater.dead&&!this.bossDefeated){this.bossDefeated=true;this.storyKicker='THE LIGHT REMEMBERS';this.storyLine='Inside the Eater: a name, still warm. “Mara. Last bearer.”';this.storyTimer=6.5;this.storyBeat=7;this.toast='THE CHAPEL OPENS';this.toastTimer=4;this.endingTimer=7;this.addBurst(eater.x,eater.y+70,'flare',70);try{localStorage.setItem('flikker-progress','chapel-open');}catch{}}
  if(this.bossDefeated){this.endingTimer-=dt;if(this.endingTimer<=0)this.mode='ending';}this.camera.x=lerp(this.camera.x,clamp(p.x-VW*.35,0,WORLD_WIDTH-VW),Math.min(1,dt*4.5));this.camera.shake=this.shake;this.audio.tension(p.lantern/p.maxLantern);this.input.jump=false;this.input.dash=false;this.input.attack=false;this.input.burst=false;this.input.special=false;
 }
 private attack(){const p=this.player;if(this.comboWindow<=0)this.combo=0;this.combo=this.combo%3+1;this.comboWindow=.42;p.attackTimer=.31;p.attackCooldown=.22;this.audio.attack();const range=this.combo===3?96:76;const hb={x:p.facing>0?p.x+6:p.x-range+24,y:p.y+(this.combo===3?-8:4),w:range,h:this.combo===3?68:54};for(const e of this.enemies){if(e.dead||!overlap(hb,e))continue;if((e.kind==='eater'||e.kind==='warden')&&!e.vulnerable)continue;const dmg=this.combo===3?2:1;e.hp-=dmg;e.hitFlash=.2;e.vx=p.facing*(300+this.combo*50);e.vy=this.combo===3?-360:-220;this.hitStop=.075;this.shake=.3;this.audio.hit();this.sparks(e.x+e.w/2,e.y+e.h/2,this.combo===3?'#d8f0d8':'#e8c87b',12);if(e.hp<=0){e.dead=true;this.addBurst(e.x+e.w/2,e.y+e.h/2,'flare',35);}}this.slash(p.x+p.facing*30,p.y+24,this.combo);}
 private lumenStep(){const p=this.player;p.lantern-=28;this.specialCooldown=2.2;this.specialTimer=.34;p.invuln=.45;p.vx=p.facing*720;p.vy=-80;this.specialRing=1;this.audio.dash();this.addBurst(p.x+15,p.y+25,'flare',28);for(const e of this.enemies){if(e.dead||!overlap({x:p.x-30,y:p.y-12,w:110,h:84},e))continue;e.hp-=2;e.hitFlash=.3;e.vx=p.facing*430;e.vy=-280;this.sparks(e.x+e.w/2,e.y+e.h/2,'#d6f3dd',18);if(e.hp<=0)e.dead=true;}this.shake=.6;this.toast='LUMEN STEP';this.toastTimer=.8;}
 private reveal(){for(const e of this.enemies){if(e.dead)continue;if(Math.hypot(this.player.x-e.x,this.player.y-e.y)<350){e.vulnerable=true;e.alert=1;if(e.kind==='eater'||e.kind==='warden')e.attackWindup=.01;}}}
  private horizontal(body:{x:number;y:number;w:number;h:number;vx:number;vy:number;grounded:boolean},oldX:number,surfaces:Platform[]){if(body.vx===0)return;for(const s of surfaces){if(s.oneWay)continue;const y=this.platformY(s.x,s.y);if(body.y+body.h<=y+4||body.y>=y+s.h)continue;if(body.x<body.x+body.w&&body.x+body.w>s.x&&oldX+body.w<=s.x&&body.vx>0){body.x=s.x-body.w-.01;body.vx=0;}else if(body.x<s.x+s.w&&body.x+body.w>s.x&&oldX>=s.x+s.w&&body.vx<0){body.x=s.x+s.w+.01;body.vx=0;}}}
  private vertical(body:{x:number;y:number;w:number;h:number;vy:number;grounded:boolean},oldY:number,surfaces:Platform[]){if(body.vy<0)return;let land:Platform|undefined;for(const s of surfaces){const y=this.platformY(s.x,s.y);const crossed=oldY+body.h<=y+4&&body.y+body.h>=y;if(crossed&&body.x+body.w>s.x+3&&body.x<s.x+s.w-3&&(!s.oneWay||oldY+body.h<=y+2)&&(!land||y<this.platformY(land.x,land.y)))land=s;}if(land){body.y=this.platformY(land.x,land.y)-body.h;body.vy=0;body.grounded=true;}}
 private platformY(x:number,y:number){return x>1600&&x<3000?y+Math.sin(this.time*.9+x*.012)*7:y;}
 private story(){if(this.bossDefeated||this.storyBeat>=beats.length-1)return;const n=beats[this.storyBeat+1];if(this.player.x>=n[2]){this.storyBeat++;this.storyKicker=n[0];this.storyLine=n[1];this.storyTimer=n[3];this.toast=n[0];this.toastTimer=2.2;this.addBurst(this.player.x,this.player.y,'gold',18);this.audio.tone(184,.3,'sine',.04,50);}}
 private checkpoints(){for(let i=0;i<checkpoints.length;i++)if(this.player.x>checkpoints[i].x-100&&i>this.checkpoint){this.checkpoint=i;checkpoints[i].activated=true;this.player.health=this.player.maxHealth;this.player.lantern=Math.min(100,this.player.lantern+40);this.toast=`checkpoint · ${checkpoints[i].area.toLowerCase()}`;this.toastTimer=2.5;this.addBurst(checkpoints[i].x,checkpoints[i].y-45,'gold',35);}}
 private respawn(){const c=checkpoints[this.checkpoint];this.player.x=c.x;this.player.y=c.y-this.player.h-6;this.player.vx=0;this.player.vy=0;this.player.health=this.player.maxHealth;this.player.lantern=Math.max(48,this.player.lantern);this.player.invuln=1;this.toast='The lantern pulls you back';this.toastTimer=2.2;this.addBurst(this.player.x,this.player.y+35,'flare',30);}
  private enemiesUpdate(dt:number){const p=this.player;for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);e.attackTimer-=dt;e.attackWindup=Math.max(0,e.attackWindup-dt);e.phase=(e.phase||0)+dt;const d=p.x-e.x;const lit=Math.hypot(p.x-e.x,p.y-e.y)<210+p.lantern*1.5||p.burstTimer>0||this.specialTimer>0;if(e.kind!=='eater'&&e.kind!=='warden'&&!lit){e.vx=lerp(e.vx,0,dt*3);continue;}e.facing=d<0?-1:1;if(e.kind==='eater'||e.kind==='warden'){const w=e.kind==='warden';if(Math.abs(d)<520)e.alert=1;if(e.attackTimer<0){e.attackWindup=w?.72:.6;e.attackTimer=w?2:2.35;this.toast=w?'THE BELL WARDEN TURNS':'THE EATER STIRS';this.toastTimer=.8;this.audio.boss();}if(e.attackWindup<=0&&e.attackTimer>(w?1.1:2.2)&&Math.abs(d)<(w?600:540))this.hurt(1,Math.sign(d)||1);e.vulnerable=p.burstTimer>0||this.specialTimer>0||e.attackWindup>.1;e.vx=lerp(e.vx,clamp(d*(w?.55:.42),-145,145),dt*1.6);}else if(e.kind==='watcher'){e.vx=lerp(e.vx,0,dt*4);if(e.attackTimer<0&&Math.abs(d)<450){e.attackTimer=2.5;e.attackWindup=.62;}if(e.attackWindup>.18&&e.attackWindup<.22&&Math.abs(d)<430)this.hurt(1,Math.sign(d)||1);e.vulnerable=e.attackWindup>.3;}else if(e.kind==='skitter'){e.vx=lerp(e.vx,clamp(d*1.4,-180,180),dt*2.8);if(e.attackTimer<0&&Math.abs(d)<120){e.attackTimer=1.5;e.attackWindup=.24;}if(e.attackWindup<=0&&e.attackTimer>1.28&&Math.abs(d)<125)this.hurt(1,Math.sign(d)||1);e.vulnerable=e.hitFlash>0;}else{e.vx=lerp(e.vx,clamp(d*.8,-110,110),dt*1.8);e.vulnerable=true;}const ex=e.x,ey=e.y;e.x+=e.vx*dt;e.x=clamp(e.x,0,WORLD_WIDTH-e.w);this.horizontal(e,ex,platforms);e.y+=e.vy*dt;e.vy+=1500*dt;e.grounded=false;this.vertical(e,ey,platforms);if(e.y>WORLD_HEIGHT){e.y=0;e.vy=0;}if(e.kind!=='eater'&&overlap(p,e)&&p.invuln<=0)this.hurt(1,Math.sign(p.x-e.x)||1);}}
  private hurt(d:number,dir:number){const p=this.player;if(p.invuln>0||this.specialTimer>0)return;p.health-=d;p.invuln=.85;p.hurtFlash=.35;p.hurtTimer=.3;p.vx=dir*300;p.vy=-280;this.shake=.8;this.horror=.65;this.redFlash=.9;this.hitStop=.075;this.audio.hurt();this.sparks(p.x,p.y+20,'#b95c63',10);this.addBurst(p.x+15,p.y+22,'gold',8);if(p.health<=0)this.respawn();}
 private ghost(){const a=[340,980,1920,2880,3740,4780,5850,7040];let i=0;for(let n=0;n<a.length;n++)if(this.player.x>a[n]-180)i=n;const x=a[i],near=Math.abs(this.player.x-x),visible=!this.bossDefeated&&this.player.x>x-230&&this.player.x<x+175;this.ghostGesture=near<35?'vanish':near<70?'watch':near<135?'wait':'point';return{x,y:465-(i%2)*56,visible};}
 private updateParticles(dt:number){this.particles=this.particles.filter(q=>q.life>0).slice(-350);for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=(q.gravity===undefined?280:q.gravity)*dt;}this.dashTrail=this.dashTrail.map(t=>({x:t.x,y:t.y,a:t.a-dt*5})).filter(t=>t.a>0);}
 private dust(x:number,y:number,n:number,color='#9da79e'){for(let i=0;i<n;i++)this.particles.push({x:x+(Math.random()-.5)*28,y:y+Math.random()*7,vx:(Math.random()-.5)*35,vy:-Math.random()*30,life:.45+Math.random()*.55,maxLife:1,size:1+Math.random()*2.5,color,gravity:-5});}
 private sparks(x:number,y:number,color:string,n:number){for(let i=0;i<n;i++)this.particles.push({x,y,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,life:.2+Math.random()*.3,maxLife:.5,size:1+Math.random()*2.5,color});}
 private addBurst(x:number,y:number,type:'gold'|'flare'='gold',n=30){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*170;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.5,maxLife:1,size:1+Math.random()*3,color:type==='flare'?(Math.random()>.25?'#e5f4dc':'#e9c96f'):'#d7d0a0'});}}
 private slash(x:number,y:number,step:number){for(let i=0;i<16;i++){const a=-1.15+i/15*1.9;this.particles.push({x:x+Math.cos(a)*22,y:y+Math.sin(a)*22,vx:Math.cos(a)*20,vy:Math.sin(a)*20,life:.15,maxLife:.18,size:2+step*.35,color:step===3?'#d7f0d9':'#e9c87d'});}}
 private addDashTrail(){this.dashTrail.push({x:this.player.x+15,y:this.player.y+27,a:1});if(this.dashTrail.length>12)this.dashTrail.shift();}
  private render(){const c=this.ctx,s=Math.min(this.canvas.width/VW,this.canvas.height/VH),ox=(this.canvas.width-VW*s)/2,oy=(this.canvas.height-VH*s)/2;c.save();c.clearRect(0,0,this.canvas.width,this.canvas.height);c.translate(ox,oy);c.scale(s,s);const sh=this.settings.screenShake?this.camera.shake*(Math.random()-.5)*8:0;c.translate(sh,sh*.4);this.sky(c);c.save();c.translate(-this.camera.x*.1,0);this.far(c);c.restore();c.save();c.translate(-this.camera.x*.28,0);this.mid(c);c.restore();c.save();c.translate(-this.camera.x,0);this.world(c);c.restore();this.fog(c);this.darkness(c,ox,oy,s);this.horrorOverlay(c);c.restore();}
  private sky(c:CanvasRenderingContext2D){const g=c.createLinearGradient(0,0,0,VH);g.addColorStop(0,'#02050b');g.addColorStop(.42,'#0a111a');g.addColorStop(.78,'#171a1c');g.addColorStop(1,'#241d1d');c.fillStyle=g;c.fillRect(0,0,VW,VH);const m=c.createRadialGradient(880,170,4,880,170,340);m.addColorStop(0,'rgba(175,205,193,.13)');m.addColorStop(.48,'rgba(95,36,46,.05)');m.addColorStop(1,'rgba(210,232,221,0)');c.fillStyle=m;c.fillRect(0,0,VW,VH);for(const s of this.stars){const x=(s.x+this.time*s.s*5)%VW;c.globalAlpha=.08+(s.x%6)*.025;c.fillStyle=s.x%11===0?'#b45c62':'#b8ccc1';c.fillRect(x,s.y+Math.sin(this.time*s.s+s.x)*4,s.x%7===0?2:1,1);}c.globalAlpha=1;}
 private far(c:CanvasRenderingContext2D){c.fillStyle='#0d1822';for(let x=-300;x<WORLD_WIDTH+500;x+=240){const h=130+Math.abs((x*7)%150);c.beginPath();c.moveTo(x,600);c.lineTo(x+20,600-h);c.lineTo(x+80,600-h-18);c.lineTo(x+155,600);c.closePath();c.fill();}}
 private mid(c:CanvasRenderingContext2D){for(let x=-80;x<WORLD_WIDTH+500;x+=360){const h=100+(Math.sin(x*.08)+1)*35;c.fillStyle='#141f25';c.fillRect(x,625-h,24,h);c.fillRect(x+108,625-h*.72,27,h*.72);c.fillStyle='#1d2a2d';c.fillRect(x-12,625-h,152,10);c.strokeStyle='rgba(93,133,121,.2)';c.lineWidth=2;c.beginPath();c.moveTo(x+10,625);c.quadraticCurveTo(x+60,535,x+114,625);c.stroke();}}
 private world(c:CanvasRenderingContext2D){this.architecture(c);for(const p of platforms)this.platform(c,p);this.checkpointDraw(c);this.ghostDraw(c);for(const e of this.enemies)if(!e.dead)this.enemy(c,e);this.playerDraw(c);for(const q of this.particles){c.globalAlpha=clamp(q.life/q.maxLife,0,1);c.fillStyle=q.color;c.beginPath();c.arc(q.x,q.y,q.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;}
 private architecture(c:CanvasRenderingContext2D){const a=areaAt(this.player.x);if(a==='THE THRESHOLD'||a==='THE HOLLOW'){c.strokeStyle='rgba(102,125,116,.38)';c.lineWidth=7;c.beginPath();c.moveTo(520,662);c.lineTo(520,420);c.quadraticCurveTo(615,300,710,420);c.lineTo(710,662);c.stroke();}if(a==='SHIFTING HALL'){for(let x=1720;x<2940;x+=210){c.fillStyle='#263331';c.fillRect(x,390,25,270);c.fillRect(x+125,430,19,230);c.strokeStyle='rgba(190,165,108,.2)';c.strokeRect(x+26,455,98,68);}}if(a==='THE SUNKEN GARDEN'){c.strokeStyle='rgba(79,120,89,.58)';c.lineWidth=4;for(let x=3080;x<3910;x+=88){c.beginPath();c.moveTo(x,700);c.bezierCurveTo(x-12,622,x+30,574,x+11,510);c.stroke();}}if(a==='THE CHAPEL'||a==='THE DESCENT'||a==='BELL CHAMBER'||a==='EATER ARENA'){c.fillStyle='#18232a';c.fillRect(4300,290,18,360);c.fillRect(4660,250,20,400);}if(a==='THE CHAPEL'||a==='BELL CHAMBER'){c.strokeStyle='rgba(210,181,112,.3)';c.lineWidth=3;c.beginPath();c.moveTo(5800,230);c.lineTo(5800,520);c.arc(5800,545,56,Math.PI,Math.PI*2);c.stroke();}}
 private platform(c:CanvasRenderingContext2D,p:Platform){const y=this.platformY(p.x,p.y);const water=p.material==='water',wood=p.material==='wood';c.fillStyle=water?'#243e43':wood?'#40382d':'#27343a';c.fillRect(p.x,y,p.w,p.h);c.fillStyle=water?'#57847b':'#52615a';c.fillRect(p.x-2,y,p.w+4,10);if(p.moss){c.strokeStyle='#66805f';c.lineWidth=2;for(let x=p.x+15;x<p.x+p.w-14;x+=28){c.beginPath();c.moveTo(x,y+5);c.quadraticCurveTo(x-3,y-5,x+4,y-13);c.stroke();}}}
 private checkpointDraw(c:CanvasRenderingContext2D){for(let i=0;i<checkpoints.length;i++){const q=checkpoints[i],active=i<=this.checkpoint;c.strokeStyle=active?'rgba(229,190,104,.8)':'rgba(120,140,132,.25)';c.lineWidth=2;c.beginPath();c.moveTo(q.x,q.y);c.lineTo(q.x,q.y-66);c.stroke();c.fillStyle=active?'rgba(239,198,111,.25)':'rgba(120,150,140,.06)';c.beginPath();c.arc(q.x,q.y-71,active?20:12,0,Math.PI*2);c.fill();}}
 private ghostDraw(c:CanvasRenderingContext2D){const g=this.ghost();if(!g.visible)return;c.save();c.translate(g.x,g.y+Math.sin(this.time*1.5)*5);c.globalCompositeOperation='screen';const h=c.createRadialGradient(0,-15,3,0,-15,95);h.addColorStop(0,'rgba(220,255,235,.3)');h.addColorStop(1,'rgba(130,215,190,0)');c.fillStyle=h;c.beginPath();c.arc(0,-15,95,0,Math.PI*2);c.fill();c.fillStyle='rgba(176,224,204,.9)';c.beginPath();c.moveTo(-24,-5);c.quadraticCurveTo(-18,-28,0,-30);c.quadraticCurveTo(18,-28,24,-5);c.lineTo(32,34);c.quadraticCurveTo(12,28,0,46);c.quadraticCurveTo(-12,28,-32,34);c.closePath();c.fill();c.fillStyle='#efffe9';c.fillRect(-4,-28,2,2);c.fillRect(2,-28,2,2);c.restore();}
 private enemy(c:CanvasRenderingContext2D,e:Enemy){const cx=e.x+e.w/2,cy=e.y+e.h/2;c.save();c.translate(cx,cy);c.scale(e.facing||1,1);const hitc=e.hitFlash>0,tele=e.attackWindup>.05;c.fillStyle=e.kind==='eater'?'#17282d':e.kind==='warden'?'#1a2c31':hitc?'#e9dfbc':'#31464a';if(e.kind==='skitter'){c.beginPath();c.ellipse(0,0,29,18,0,0,Math.PI*2);c.fill();}else if(e.kind==='watcher'){c.beginPath();c.ellipse(0,0,25,38,0,0,Math.PI*2);c.fill();}else{c.beginPath();c.ellipse(0,0,e.w*.38,e.h*.42,0,0,Math.PI*2);c.fill();}c.fillStyle=tele?'#ef9d62':'#d9ca87';c.beginPath();c.arc(0,-18,6,0,Math.PI*2);c.fill();if(e.vulnerable&&(e.kind==='eater'||e.kind==='warden')){c.strokeStyle='rgba(215,244,220,.8)';c.lineWidth=3;c.beginPath();c.arc(0,0,Math.max(e.w,e.h)*.55,0,Math.PI*2);c.stroke();}c.restore();if(e.hp<e.maxHp&&e.kind!=='eater'){c.fillStyle='rgba(6,12,16,.8)';c.fillRect(e.x-2,e.y-12,e.w+4,5);c.fillStyle='#d2b76e';c.fillRect(e.x,e.y-11,e.w*e.hp/e.maxHp,3);}}
 private playerDraw(c:CanvasRenderingContext2D){const p=this.player;let state='idle';if(p.hurtTimer&&p.hurtTimer>0)state='hurt';else if(p.dashTimer>0)state='dash';else if(this.specialTimer>0)state='special';else if(p.attackTimer>0)state='attack';else if(p.burstTimer>0)state='flare';else if(!p.grounded)state=p.vy<0?'jump':'fall';else if(Math.abs(p.vx)>35)state='run';const run=Math.sin((p.runTime||0))*(state==='run'?1:0);c.save();for(const t of this.dashTrail){c.globalAlpha=t.a*.18;c.fillStyle='#d9e8d8';c.beginPath();c.arc(t.x,t.y,16,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.translate(p.x+15,p.y+27+run*2);c.scale(p.facing,1);c.fillStyle='rgba(224,184,87,.14)';c.beginPath();c.arc(19,3,38,0,Math.PI*2);c.fill();const cloak=c.createLinearGradient(-20,-38,20,35);cloak.addColorStop(0,'#47616a');cloak.addColorStop(.45,'#1b303b');cloak.addColorStop(1,'#08151f');c.fillStyle=cloak;c.beginPath();c.moveTo(-18,31);c.quadraticCurveTo(-30,10,-22,-13);c.quadraticCurveTo(-17,-34,0,-38);c.quadraticCurveTo(22,-34,23,-8);c.lineTo(18,32);c.lineTo(8,25);c.lineTo(0,35);c.lineTo(-8,25);c.closePath();c.fill();c.fillStyle='#9eb4ae';c.beginPath();c.arc(1,-26,13,0,Math.PI*2);c.fill();c.fillStyle='#111d25';c.beginPath();c.moveTo(-15,-29);c.quadraticCurveTo(0,-49,18,-32);c.lineTo(11,-25);c.lineTo(-15,-26);c.closePath();c.fill();c.fillStyle='#e2bd62';c.beginPath();c.arc(19,4,6+(p.burstTimer>0?5:0),0,Math.PI*2);c.fill();if(state==='attack'){c.strokeStyle='#f1d68c';c.lineWidth=5;c.beginPath();c.arc(18,0,38,-1.2,.7);c.stroke();}if(state==='special'){c.strokeStyle='#d6f3dd';c.lineWidth=4;c.beginPath();c.arc(0,0,52+Math.sin(this.time*18)*5,0,Math.PI*2);c.stroke();}if(state==='flare'){c.strokeStyle='#e1f3db';c.lineWidth=3;c.beginPath();c.arc(18,4,44+Math.sin(this.time*16)*5,0,Math.PI*2);c.stroke();}c.restore();}
 private fog(c:CanvasRenderingContext2D){c.save();c.globalCompositeOperation='screen';for(let i=0;i<5;i++){const x=(this.time*(8+i*4)+i*230)%(VW+500)-250,y=420+i*40+Math.sin(this.time*.2+i)*14,g=c.createRadialGradient(x,y,5,x,y,270);g.addColorStop(0,'rgba(170,190,180,.1)');g.addColorStop(1,'rgba(170,190,180,0)');c.fillStyle=g;c.beginPath();c.ellipse(x,y,290,34,0,0,Math.PI*2);c.fill();}c.restore();}
  private horrorOverlay(c:CanvasRenderingContext2D){const p=this.player,e=p.lantern/p.maxLantern;const intensity=Math.max(this.horror,(1-e)*.34);if(intensity<=.01&&!this.redFlash)return;c.save();c.globalCompositeOperation='screen';c.globalAlpha=.22*intensity;const vignette=c.createRadialGradient(VW/2,VH/2,180,VW/2,VH/2,700);vignette.addColorStop(0,'rgba(70,12,22,0)');vignette.addColorStop(.7,'rgba(70,12,22,.2)');vignette.addColorStop(1,'rgba(12,0,4,.8)');c.fillStyle=vignette;c.fillRect(0,0,VW,VH);if(intensity>.45){c.globalAlpha=.22*intensity;for(let i=0;i<6;i++){const x=(i*229+this.time*(i%2?7:-5))%VW,y=210+(i*71)%270; c.fillStyle=i%2?'#741e38':'#a0343e';c.beginPath();c.ellipse(x,y,3+intensity*3,1.5,0,0,Math.PI*2);c.fill();}}if(this.redFlash>0){c.globalAlpha=this.redFlash*.16;c.fillStyle='#b82438';c.fillRect(0,0,VW,VH);}c.restore();}
  private darkness(c:CanvasRenderingContext2D,ox:number,oy:number,s:number){const p=this.player,e=p.lantern/p.maxLantern,sx=(p.x-this.camera.x+15)*s+ox,sy=(p.y+27)*s+oy,r=(104+e*158)*(this.settings.reducedFlicker?1:1+Math.sin(this.time*15)*.045+Math.sin(this.time*31)*(1-e)*.06)*s;c.save();c.fillStyle=`rgba(0,3,8,${clamp(.8-e*.22,.5,.84)})`;c.fillRect(0,0,VW,VH);const g=c.createRadialGradient(sx,sy,r*.06,sx,sy,r);g.addColorStop(0,'rgba(255,238,185,.25)');g.addColorStop(.38,'rgba(16,23,27,.04)');g.addColorStop(1,'rgba(0,0,0,.98)');c.globalCompositeOperation='destination-out';c.fillStyle=g;c.beginPath();c.arc(sx,sy,r,0,Math.PI*2);c.fill();c.globalCompositeOperation='screen';const bloom=c.createRadialGradient(sx,sy,0,sx,sy,r*.62);bloom.addColorStop(0,'rgba(255,207,111,.32)');bloom.addColorStop(.38,'rgba(207,92,65,.06)');bloom.addColorStop(1,'rgba(255,205,112,0)');c.fillStyle=bloom;c.beginPath();c.arc(sx,sy,r*.62,0,Math.PI*2);c.fill();if(this.ring>0){c.strokeStyle=`rgba(215,242,222,${this.ring})`;c.lineWidth=3;c.beginPath();c.arc(sx,sy,(1-this.ring)*380*s,0,Math.PI*2);c.stroke();}if(this.specialRing>0){c.strokeStyle=`rgba(230,248,225,${this.specialRing})`;c.lineWidth=2;c.beginPath();c.arc(sx,sy,(1-this.specialRing)*250*s,0,Math.PI*2);c.stroke();}c.restore();}
}
